---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname tinyauth
spec:
  dataFrom:
    - extract:
        key: bazarr
    - extract:
        key: tinyauth
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        bazarr-basic-password: "{{ .TINYAUTH_BASIC_PASSWORD }}"
        key.pem: "{{ .OIDC_PRIVATE_KEY }}"
        key.pub: "{{ .OIDC_PUBLIC_KEY }}"
        immich-client-secret: "{{ .IMMICH_CLIENT_SECRET }}"
