---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etcd-defrag
spec:
  chartRef:
    kind: OCIRepository
    name: etcd-defrag
  interval: 1h
  values:
    defaultPodOptions:
      automountServiceAccountToken: true
      hostNetwork: true
      hostPID: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
    controllers:
      etcd-defrag:
        type: cronjob
        cronjob:
          schedule: "@daily"
          suspend: true
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/ahrtr/etcd-defrag
              tag: v0.44.0@sha256:0b345057de8a5915031e656546ef490b44f8bc85e68df26688147f9f0da2c4ff
            args:
              - --endpoints=https://127.0.0.1:2379
              - --cluster
              - --cacert=/certs/ca.crt
              - --cert=/certs/admin.crt
              - --key=/certs/admin.key
              - --defrag-rule=dbQuotaUsage > 0.5 || dbSizeFree > 100*1024*1024
              - --move-leader
              - --wait-between-defrags=30s
              - --etcd-storage-quota-bytes=2147483648
              - --auto-disalarm
              - --disalarm-threshold=0.8
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 128Mi
            securityContext:
              privileged: true
    persistence:
      certs:
        type: hostPath
        hostPath: /system/secrets/etcd
        globalMounts:
          - path: /certs
            readOnly: true
      tmp:
        type: emptyDir
        advancedMounts:
          etcd-defrag:
            app:
              - path: /tmp
                subPath: tmp
