---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/media/paperless/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-tika
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  interval: 1h
  path: ./kubernetes/apps/media/paperless/tika
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-gotenberg
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  interval: 1h
  path: ./kubernetes/apps/media/paperless/gotenberg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-app
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: paperless-database
    - name: paperless-tika
    - name: paperless-gotenberg
  interval: 1h
  path: ./kubernetes/apps/media/paperless/app
  postBuild:
    substitute:
      APP: paperless
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: true
