---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-operator
spec:
  chartRef:
    kind: OCIRepository
    name: vm-operator
  interval: 1h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    fullnameOverride: vm-operator

    crds:
      enabled: true
      upgrade:
        enabled: true
        forceConflicts: true

    operator:
      disable_prometheus_converter: false
      enable_converter_ownership: true

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi

    serviceMonitor:
      enabled: true
      vm: true
