---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-tls
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kanidm-tls
    creationPolicy: Orphan
    template:
      type: kubernetes.io/tls
      metadata:
        annotations:
          cert-manager.io/alt-names: "*.dcunha.io,dcunha.io"
          cert-manager.io/certificate-name: dcunha.io
          cert-manager.io/common-name: dcunha.io
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/issuer-name: letsencrypt-production
        labels:
          controller.cert-manager.io/fao: "true"
  dataFrom:
    - extract:
        key: dcunha-io-tls
        decodingStrategy: Base64
