---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pve-ca-cert
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIF3TCCA8WgAwIBAgIUNMFWtk8wI9czlte0OArsSDirn7owDQYJKoZIhvcNAQEL
    BQAwdjEkMCIGA1UEAwwbUHJveG1veCBWaXJ0dWFsIEVudmlyb25tZW50MS0wKwYD
    VQQLDCRjZWNhOGU1Ny1mNGJmLTQwMzUtOWZiMy0wOTAzMTYxMGRiY2YxHzAdBgNV
    BAoMFlBWRSBDbHVzdGVyIE1hbmFnZXIgQ0EwHhcNMjYwNTMwMjMyODE0WhcNMzYw
    NTI3MjMyODE0WjB2MSQwIgYDVQQDDBtQcm94bW94IFZpcnR1YWwgRW52aXJvbm1l
    bnQxLTArBgNVBAsMJGNlY2E4ZTU3LWY0YmYtNDAzNS05ZmIzLTA5MDMxNjEwZGJj
    ZjEfMB0GA1UECgwWUFZFIENsdXN0ZXIgTWFuYWdlciBDQTCCAiIwDQYJKoZIhvcN
    AQEBBQADggIPADCCAgoCggIBAJQHGzo0O7AgVDAb7izx1Ar9QMCvCocsNKO/AGTC
    iAst0t9Ajk21XRMG34I5AChxrxNQutQ7whQaE1Zrxqq4KrTAByswWorD1Hc69K2W
    cWJVdZIOQ+gnJFcjBiKmwVvY1xXJfDsL+nCGTu9BNv7ETSA4ljkYQFpG7DvYGDmk
    0rL+8vVNvvzTXVAG7qbIE38FQBh+daPmWL2LhoBsvHu54nr9tXj3vrVJy8SsGVow
    s/Ch539RGaS9PFoGw2+HjslHeT6p5dUiHiNsBvnxuGdQ5b0Ihci+r3HkNaSQhbfe
    nJIrkatF40NMgTinWqLWP3CNe6T1JYSxweQrv9FoSU8fyA00w4MZyhERdQN6Uycx
    yZvpaX/OSGnTESS/S6EfwyI4Ty5uXjNPI5XRR744IkbpzUd7cidhQyLw9pOk/0sI
    5BgZweR3QBvNbe7fSPk+NOKTfoRgQ2+5sEdWQT3bSh0MlArSQtf+7N3qMGmyhUrh
    Tc8wAfemJnRCXL/xB2SIEh6QGryVfm6ObqU7/OT5hxVGpBLrSd7UItDjzicHmEfe
    65mnrrIIArtoMZQNVqHfgYoOa9WRFcu8ibDJmai3McnD8T+ZH72C1j6YxzW6bdKb
    +cn4G+pEfhQch9pU6hMYOMXzzjLYgIAg7EypxW9ucnTFUg6F0h/g0m6TsxhwgFsE
    X0e5AgMBAAGjYzBhMB0GA1UdDgQWBBT6gszImsUJ+H7/ACMPZqcXqOgHRTAfBgNV
    HSMEGDAWgBT6gszImsUJ+H7/ACMPZqcXqOgHRTAPBgNVHRMBAf8EBTADAQH/MA4G
    A1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAgEABm9pBzIxcB9FmSS1JBpL
    MhN4evehtIFHTVTeYz4Boc2JS4TgZSmWk+Qj8VCfKMXWfYmwiunsdV3RHzCLrqoa
    1afLVTfQmOziIQAa4PsdFyYj87OH3zmwhCm2JFitu1Waj0uxSjLALSrge3EWVbaJ
    7jzDz83ONGbAub5HiPK2aDn7wD4LnBWTQGzkN64mwAiYyJ4NMoq6qR7aWOKl882D
    apKvQY7JmpJ9iALayw5VUCXPTgrJsjB7sEIs/qBmLSujGMcnpgAtfSUQuQ2klInN
    Qeq+w3bLiga8VB8brkE5Q3kLsVYlLfDHT9ncDtRUPmhZhqGjLvbUx7oxsMinrZGk
    62cFGrtQvG/tFgBRmP3nX3jGIElFBOAuZjza4iiEtBoxw08XWA5FUgvAMrBpebwP
    JVy3bRto/fLseCF/llpNiHChViWw+adiDVDByBEoYvQ5nFDR5Wi9JNhHtXJUmDIY
    6QQL2GqlMaJw2C66zeJBSqzCEWqhs/ngI9JRB7vSUuECqBEoQ60plT+APcs0IVmY
    Yh2vUK+Al4suquwLwzWlTgsNT/YmRgI4emNrn/IHJjBXf/7wTDssxI50J744mRTF
    KOzRunI9UilAPXgnyrbdXw1DpBHKLtTr0LRgsNx4ebzpL6/Pek59mFskpzqKcvV8
    XXr125Am24/lXJ823u1IE1g=
    -----END CERTIFICATE-----
