---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/fluxcd.controlplane.io/resourcesetinputprovider_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: pve
  labels:
    external-endpoint.dcunha.io/template: https
spec:
  type: Static
  defaultValues:
    name: pve
    ip: 10.10.99.104
    port: 8006
    hostname: pve.dcunha.io
    caHostname: pve.dcunha.io
    caConfigMap: pve-ca-cert
    useClientProtocol: false
