---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-sidecar
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus
    template:
      engineVersion: v2
      data:
        DDNS_HOSTNAME: "{{ .DDNS_HOSTNAME }}"
        HEARTBEAT_TOKEN: "{{ .HEARTBEAT_TOKEN }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        STATUS_HOSTNAME: "{{ .STATUS_HOSTNAME }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: gatus
