---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname xbrowsersync
spec:
  dataFrom:
    - extract:
        key: xbrowsersync
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        MONGO_INITDB_ROOT_PASSWORD: "{{ .password }}"
        MONGO_INITDB_ROOT_USERNAME: "{{ .username }}"
        XBROWSERSYNC_DB_PWD: "{{ .password }}"
        XBROWSERSYNC_DB_USER: "{{ .username }}"
