---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: "${APP}-tinyauth"
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
      - X-Forwarded-For
      - X-Forwarded-Host
      - X-Forwarded-Proto
      - X-Forwarded-Uri
      - accept
      - cookie
      - user-agent
    http:
      backendRefs:
        - name: tinyauth
          namespace: security
          port: 3000
      headersToBackend:
        - Authorization
        - Location
        - Set-Cookie
      path: /api/auth/envoy?path=
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "${HTTP_ROUTE_TARGET:-${APP}}"
