---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hermes
spec:
  targetNamespace: cortex
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/cortex/hermes/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 15m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: litellm-operator
    - name: memini
    - name: pocket-id-operator
      namespace: security
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/tinyauth
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CACHE_STORAGECLASS: ceph-block
      HTTP_ROUTE_TARGET: hermes-codeserver
      KOPIUR_CAPACITY: 20Gi
      KOPIUR_SNAPSHOTCLASS: miroir
      KOPIUR_STORAGECLASS: miroir
  wait: false
