---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: suwayomi
spec:
  chartRef:
    kind: OCIRepository
    name: suwayomi
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 6470
        runAsGroup: 6470
        fsGroup: 6470
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      suwayomi:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          01-init-config:
            image:
              repository: docker.io/library/busybox
              tag: 1.38
            command:
              - sh
              - -c
              - cp /configmap/server.conf /tachidesk-data/server.conf
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.2.2166@sha256:0839e707599b533e9c9160b3364396c47ad0dff9d4a8501d3cdf18013e5cdf90
            env:
              BIND_PORT: &port 4567
              JAVA_TOOL_OPTIONS: "-Dpolyglot.engine.WarnInterpreterOnly=false"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 60
                  periodSeconds: 5
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          suwayomi:
            01-init-config:
              - path: /tachidesk-data
            app:
              - path: /home/suwayomi/.local/share/Tachidesk
      config-file:
        type: configMap
        name: suwayomi
        advancedMounts:
          suwayomi:
            01-init-config:
              - path: /configmap
                readOnly: true
      media:
        type: nfs
        path: /mnt/atlas/media
        server: 10.10.99.100
        advancedMounts:
          suwayomi:
            app:
              - path: /home/suwayomi/.local/share/Tachidesk/downloads/mangas
                subPath: downloads/suwayomi
      tmp:
        type: emptyDir
        advancedMounts:
          suwayomi:
            app:
              - path: /tmp
                subPath: tmp

    route:
      app:
        hostnames:
          - "suwayomi.dcunha.io"
        parentRefs:
          - name: external-gateway
            namespace: network

    service:
      app:
        ports:
          http:
            port: *port
