---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: suwayomi
  namespace: media
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: suwayomi
  oidc:
    provider:
      issuer: https://auth.dcunha.io
    clientID: suwayomi
    clientSecret:
      name: suwayomi
    redirectURL: "https://suwayomi.dcunha.io/oauth2/callback"
    scopes:
      - openid
      - profile
      - email
    forwardAccessToken: false
