---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./autobrr/ks.yaml
  - ./autopulse/ks.yaml
  - ./bazarr/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./kapowarr/ks.yaml
  - ./kamiyomu/ks.yaml
  - ./komf/ks.yaml
  - ./suwayomi/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./shelfmark/ks.yaml
  - ./sonarr/ks.yaml
  - ./streamystats/ks.yaml
  - ./thelounge/ks.yaml
