---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
spec:
  chartRef:
    kind: OCIRepository
    name: node-red
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      node-red:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: nodered/node-red
              tag: 4.1.10-18-minimal@sha256:1e0732248f450e0a0163a3597a7971c8dc82492938069b3702b716ba01457b9b
            env:
              FLOWS: "flows.json"
              NODE_RED_ENABLE_PROJECTS: "true"
              NODE_RED_ENABLE_SAFE_MODE: "false"
              NODE_RED_PORT: &port 1880
              HA_URL: http://home-assistant.home-automation.svc.cluster.local:8123
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 150m
                memory: 350Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false # Node-RED writes to /data at runtime
              capabilities: {drop: ["ALL"]}
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        advancedMounts:
          node-red:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
