---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-microservices
spec:
  chartRef:
    kind: OCIRepository
    name: immich-microservices
  interval: 1h
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.7.5
            env:
              DB_DATABASE_NAME: immich
              DB_HOSTNAME: immich-database-postgres.default.svc.cluster.local
              DB_USERNAME: immich
              IMMICH_CONFIG_FILE: /config/immich.json
              IMMICH_MACHINE_LEARNING_URL: http://immich-ml.default.svc.cluster.local:3003
              IMMICH_WORKERS_EXCLUDE: api
              REDIS_HOSTNAME: immich-database-redis.default.svc.cluster.local
            envFrom:
              - secretRef:
                  name: immich
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    persistence:
      library:
        type: nfs
        server: 10.10.99.100
        path: /mnt/atlas/media/photos
        advancedMounts:
          app:
            app:
              - path: /usr/src/app/upload
      config:
        type: secret
        name: immich
        advancedMounts:
          app:
            app:
              - path: /config/immich.json
                subPath: immich.json
                readOnly: true
      tmp:
        type: emptyDir
        advancedMounts:
          app:
            app:
              - path: /tmp
                subPath: tmp
