---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: external-service-http
spec:
  wait: true
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      selector:
        matchLabels:
          external-endpoint.dcunha.io/template: http
  resources:
    - apiVersion: discovery.k8s.io/v1
      kind: EndpointSlice
      metadata:
        name: << inputs.name >>
        namespace: external-endpoints
        labels:
          kubernetes.io/service-name: << inputs.name >>
      addressType: IPv4
      endpoints:
        - addresses:
            - << inputs.ip >>
          conditions:
            ready: true
            serving: true
            terminating: false
      ports:
        - name: << inputs.protocol >>
          port: << inputs.port >>
          protocol: TCP
          appProtocol: << inputs.protocol >>
    - apiVersion: v1
      kind: Service
      metadata:
        name: << inputs.name >>
        namespace: external-endpoints
        annotations:
          gatus.home-operations.com/enabled: "true"
          gatus.home-operations.com/endpoint: |-
            url: "<< inputs.gatus >>"
            group: homelab
            interval: 1m
            ui:
              hide-hostname: true
              hide-url: true
            conditions:
              - "[STATUS] == 200"
      spec:
        clusterIP: None
        ports:
          - name: << inputs.protocol >>
            port: << inputs.port >>
            protocol: TCP
            targetPort: << inputs.port >>
            appProtocol: << inputs.protocol >>
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: << inputs.name >>
        namespace: external-endpoints
        annotations:
          external-dns.alpha.kubernetes.io/internal: "true"
          gatus.home-operations.com/enabled: "false"
        labels:
          app.kubernetes.io/name: << inputs.name >>
          app.kubernetes.io/instance: << inputs.name >>
      spec:
        parentRefs: << inputs.gateways | toYaml | nindent 10 >>
        hostnames:
          - << inputs.hostname >>
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: << inputs.backendName >>
                port: << inputs.backendPort >>
