---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: forgejo
spec:
  allowedUserGroups:
    - name: app-admin
  callbackUrls:
    - "https://git.dcunha.io/user/oauth2/Pocket%20ID/callback"
  launchUrl: "https://git.dcunha.io/"
  logo:
    autoGenerate: false
  pkceEnabled: false
  secret:
    storeClientSecret: false
