---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eco
spec:
  dataFrom:
    - extract:
        key: eco
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: eco
    template:
      data:
        ECO_USER_TOKEN: "{{ .ECO_USER_TOKEN }}"
