---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eco
spec:
  chartRef:
    kind: OCIRepository
    name: eco
  interval: 1h
  timeout: 15m
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      terminationGracePeriodSeconds: 300
    controllers:
      eco:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: strangeloopgames/eco-game-server
              tag: 0.14.1.1-beta@sha256:536a8f50e9d6345386c1b816dd04b5c35f96faa69c2d17ee091e73f8702efe46
            args:
              - --nogui
              - --userToken=$(ECO_USER_TOKEN)
            command:
              - ./EcoServer
            env:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              HOME: /tmp
            envFrom:
              - secretRef:
                  name: eco
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 3001
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  failureThreshold: 5
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 3001
                  periodSeconds: 10
                  failureThreshold: 90
            resources:
              requests:
                cpu: 1000m
                memory: 4Gi
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
            stdin: true
            tty: true
    persistence:
      data:
        existingClaim: eco
        advancedMounts:
          eco:
            app:
              - path: /app/Storage
                subPath: storage
              - path: /app/Configs
                subPath: configs
              - path: /app/Mods/UserCode
                subPath: mods
      tmp:
        type: emptyDir
        advancedMounts:
          eco:
            app:
              - path: /tmp
                subPath: tmp
              - path: /app/Logs
                subPath: logs
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            url: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:3001"
            conditions: ["[STATUS] == 200"]
            ui:
              hide-url: true
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 3001
      frostlink:
        hostnames:
          - "{{ .Release.Name }}.frostlink.dev"
        parentRefs:
          - name: edge-gateway
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 3001
    service:
      app:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: eco.dcunha.io
          lbipam.cilium.io/ips: 10.10.99.92
        controller: eco
        externalTrafficPolicy: Local
        ports:
          game:
            port: 3000
            protocol: UDP
          webadmin:
            port: 3001
