---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: r2-store
spec:
  configuration:
    data:
      compression: gzip
    destinationPath: s3://artemis-kopiur/barman/
    endpointURL: https://cb8e9b25dc436d997f232269a3597c61.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: barman-r2
        key: ACCESS_KEY_ID
      region:
        name: barman-r2
        key: REGION
      secretAccessKey:
        name: barman-r2
        key: SECRET_ACCESS_KEY
    wal:
      compression: zstd
  retentionPolicy: 7d
