---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-ca-cert
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDNTCCAh2gAwIBAgIJb66ODa0aUGw8MA0GCSqGSIb3DQEBCwUAMBYxFDASBgNV
    BAMTC3VuaWZpLmxvY2FsMB4XDTI1MDgzMTEwNTUwM1oXDTI3MTIwNDEwNTUwM1ow
    FjEUMBIGA1UEAxMLdW5pZmkubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQCXpNAfHTJcXfisiPsJQd1o879pVYFi1chAJaFEKPnVe53XaUXe4I+U
    +baiwMLcBMUsvFlzBFpWVU+9ZsTM8v8nXWvfCe8ZJ72MFQAIt9MLFkIMHxU80FfK
    Q7hcdnujv+J7Y6rq4Ea5mprJvdBjKxlDYu7jmEbVOoFrgLACfitCQMMmcEpAppaa
    ilj8Yqd/V8QHnmBTbONe593Q+MWuNAiOHR+nQKkGrntHuw+JBva7dJ8GULj0Cl1y
    KK+ycOjKQyGSW1zWe12qVESqfmQCw7F+SnCqPPRoTh2xoYr2oSLh6UsSG5uvqtQk
    qoCz/0ZwL7fighetNe62Div5O8KLTzCrAgMBAAGjgYUwgYIwCwYDVR0PBAQDAgL0
    MDEGA1UdJQQqMCgGCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUF
    BwMIMEAGA1UdEQQ5MDeCC3VuaWZpLmxvY2Fsgglsb2NhbGhvc3SCBVs6OjFdhwR/
    AAABhxD+gAAAAAAAAAAAAAAAAAABMA0GCSqGSIb3DQEBCwUAA4IBAQCHPP1LwHUp
    NRh7SChVXzsCAQiDrF4hGdkh/USPYaHcpTM/kwhEl6JRgHggUys9eBeKl0TOUnmi
    jDo8VWa129oaocRxWGpS0xoIas1AMLu6a+Z2Du2Mp/i11HGpVnCWL05SGRB8aKfZ
    pWU53HVt2sOC5sL1SteB3ZhJOxnPQ6SxRBozFBczooTH5hUYdRhie8RS57nPUm0B
    G40uIDvCfWYLPW+rxSzFspsZrpQPJWXP8wEGLR77iSCOfoVjoQlV8jxhc2Eh3QJz
    Uv2ZIOcqZPC0mKR2DkQiVhJA/XFF2YqZ0PA0ZfN4mb+juTLLzBu9mK7FEXbIJBJb
    Y8A3PVUsryOa
    -----END CERTIFICATE-----
