---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Image Pull

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.event.number || forgejo.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  filter:
    name: Image Pull - Filter
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get Changed Files
        id: changed-files
        uses: https://github.com/bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: kubernetes/**/*

  extract:
    if: ${{ needs.filter.outputs.changed-files != '[]' }}
    needs: filter
    name: Image Pull - Extract Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - default
          - pull
      fail-fast: false
    outputs:
      default: ${{ steps.extract.outputs.default }}
      pull: ${{ steps.extract.outputs.pull }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ matrix.branch == 'default' && forgejo.event.repository.default_branch || '' }}

      - name: Install flux-local
        run: pip install flux-local==8.2.0

      - name: Gather Images
        run: |-
          flux-local get cluster \
            --all-namespaces \
            --path kubernetes/flux/sync \
            --sources "flux-system=." \
            --enable-images \
            --only-images \
            --output json \
            --output-file images.json

      - name: Extract Images
        id: extract
        run: |-
          echo "${{ matrix.branch }}=$(jq --compact-output '.' images.json)" >> "${FORGEJO_OUTPUT}"

          echo '## Branch ${{ matrix.branch }} images' >> "${FORGEJO_STEP_SUMMARY}"
          echo '```json' >> "${FORGEJO_STEP_SUMMARY}"
          jq '.' images.json >> "${FORGEJO_STEP_SUMMARY}"
          echo '```' >> "${FORGEJO_STEP_SUMMARY}"

  diff:
    if: ${{ needs.extract.outputs.default != needs.extract.outputs.pull }}
    needs: extract
    name: Image Pull - Diff Images
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.diff.outputs.images }}
    steps:
      - name: Diff Images
        id: diff
        run: |-
          images=$(jq --compact-output --null-input \
              --argjson f1 '${{ needs.extract.outputs.default }}' \
              --argjson f2 '${{ needs.extract.outputs.pull }}' \
              '$f2 - $f1' \
          )
          echo "images=${images}" >> "${FORGEJO_OUTPUT}"

          echo '## New images to Pull' >> "${FORGEJO_STEP_SUMMARY}"
          echo '```json' >> "${FORGEJO_STEP_SUMMARY}"
          echo $images | jq >> "${FORGEJO_STEP_SUMMARY}"
          echo '```' >> "${FORGEJO_STEP_SUMMARY}"

  pull:
    if: ${{ needs.diff.outputs.images != '[]' }}
    needs: diff
    name: Image Pull - Pull Images
    runs-on: talos
    strategy:
      matrix:
        image: ${{ fromJSON(needs.diff.outputs.images) }}
      max-parallel: 4
      fail-fast: false
    env:
      MATRIX_IMAGE: ${{ matrix.image }}
    steps:
      - name: Install talosctl
        run: curl -fsSL https://raw.githubusercontent.com/siderolabs/talos/b412ffdbc29d77a81aed88be62f21bc2999afcde/website/static/install | sh

      - name: Pull Image
        run: talosctl --talosconfig /var/run/secrets/talos.dev/config --nodes $NODE image pull "${MATRIX_IMAGE}"

  success:
    if: ${{ !cancelled() }}
    needs: pull
    name: Image Pull - Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
