---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate

on:
  push:
    branches:
      - main
    paths:
      - .renovaterc.json5
      - .renovate/**.json5
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        type: boolean
        default: false
        required: true
      logLevel:
        description: Log Level
        type: choice
        default: debug
        options:
          - debug
          - info
        required: true

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.event.number || forgejo.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  main:
    name: Renovate
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Renovate
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
          RENOVATE_AUTODISCOVER: "true"
          RENOVATE_AUTODISCOVER_FILTER: ${{ forgejo.repository }}
          RENOVATE_DRY_RUN: ${{ inputs.dryRun }}
          RENOVATE_ENDPOINT: ${{ forgejo.server_url }}
          RENOVATE_PLATFORM: forgejo
          RENOVATE_TOKEN: ${{ secrets.CI_TOKEN }}
        run: npx renovate
