---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: bookboss-grpc
  namespace: default
spec:
  hostnames:
    - books.dcunha.io
  parentRefs:
    - name: external-gateway
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: bookboss
          port: 8081
