---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 5.0.3@sha256:53064020792b2e21305c892c11aaa1eb32af2141cbd59119b52df226d664cd05
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                {{ .Release.Name }},
                {{ .Release.Name }}.media,
                {{ .Release.Name }}.media.svc,
                {{ .Release.Name }}.media.svc.cluster,
                {{ .Release.Name }}.media.svc.cluster.local,
                {{ .Release.Name }}.dcunha.io
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        path: /mnt/atlas/media
        server: 10.10.99.100
        globalMounts:
          - path: /media
      scripts:
        type: configMap
        defaultMode: 0775
        name: sabnzbd-scripts
        globalMounts:
          - path: /config/scripts
            readOnly: true
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
            subPath: logs
          - path: /tmp
            subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
