---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg17
spec:
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-pg17-credentials
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE
        - CREATE EXTENSION IF NOT EXISTS cube CASCADE
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE
        - CREATE EXTENSION IF NOT EXISTS pg_trgm CASCADE
        - CREATE EXTENSION IF NOT EXISTS unaccent CASCADE
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp" CASCADE
  enableSuperuserAccess: true
  imageName: docker.io/tensorchord/cloudnative-vectorchord:17.5-0.4.3@sha256:acebb38ca309938bc05ce268b019c98aa718cb554dd54e4443654d9d00a0d498
  instances: 1
  managed:
    roles:
      - ensure: present
        login: true
        name: immich
        passwordSecret:
          name: immich-pg17-credentials
        superuser: true
  plugins:
    - isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: immich-pg17-r2-store
  postgresql:
    shared_preload_libraries:
      - vchord.so
  primaryUpdateMethod: switchover
  storage:
    size: 20Gi
    storageClass: ceph-block
  walStorage:
    size: 4Gi
    storageClass: ceph-block
