---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-pg17-credentials
spec:
  dataFrom:
    - extract:
        key: immich
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-pg17-credentials
    template:
      data:
        password: "{{ .DB_PASSWORD_CNPG }}"
        username: immich
