#!/bin/bash

sudo dmsetup remove_all && echo  "Removed Ceph dmsetup"
sudo rm -r /ceph && echo "Deleted /ceph"
sudo rm -r /var/lib/rook && echo "Delete /var/lib/rook"
sudo wipefs -a /dev/sda && echo "Device: /dev/sda wiped"
sudo wipefs -a /dev/sdb && echo "Device: /dev/sdb wiped"
sudo wipefs -a /dev/sdc && echo "Device: /dev/sdc wiped"
sudo wipefs -a /dev/sdd && echo "Device: /dev/sdd wiped"
sudo wipefs -a /dev/sde && echo "Device: /dev/sde wiped"
sudo wipefs -a /dev/sdf && echo "Device: /dev/sdf wiped"
sudo wipefs -a /dev/sdh && echo "Device: /dev/sdh wiped"
sudo wipefs -a /dev/sdi && echo "Device: /dev/sdi wiped"
sudo wipefs -a /dev/sdj && echo "Device: /dev/sdj wiped"
sudo wipefs -a /dev/sdk && echo "Device: /dev/sdk wiped"
sudo wipefs -a /dev/sdl && echo "Device: /dev/sdl wiped"
sudo wipefs -a /dev/sdm && echo "Device: /dev/sdm wiped"
sudo wipefs -a /dev/sdn && echo "Device: /dev/sdn wiped"
sudo wipefs -a /dev/sdo && echo "Device: /dev/sdo wiped"
sudo wipefs -a /dev/sdp && echo "Device: /dev/sdp wiped"
sudo wipefs -a /dev/sdr && echo "Device: /dev/sdr wiped"
