---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/pocketid.internal/pocketidinstance_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDInstance
metadata:
  name: pocket-id
spec:
  appUrl: "https://id.dcunha.io"
  databaseUrl:
    valueFrom:
      configMapKeyRef:
        name: pocket-id-postgres
        key: url
  encryptionKey:
    valueFrom:
      secretKeyRef:
        name: pocket-id
        key: ENCRYPTION_KEY
  image: ghcr.io/pocket-id/pocket-id:v2.12.0@sha256:4a277d141d6069fd9a7b321a9aca80f4b9812b8fa122ee566d2f15900e3d8448
  ldap:
    adminGroupName: lldap_admin
    attributeMapping:
      groupMember: member
      groupName: cn
      groupUniqueIdentifier: uuid
      userEmail: mail
      userFirstName: givenName
      userLastName: sn
      userProfilePicture: jpegPhoto
      userUniqueIdentifier: uuid
      userUsername: uid
    base: "dc=dcunha,dc=io"
    bindDN: "cn=admin,ou=people,dc=dcunha,dc=io"
    bindPassword:
      valueFrom:
        secretKeyRef:
          name: lldap
          key: LLDAP_LDAP_USER_PASS
    softDeleteUsers: true
    url: "ldap://lldap.security.svc.cluster.local:3890"
    userGroupSearchFilter: "(objectClass=groupOfNames)"
    userSearchFilter: "(objectClass=person)"
  metrics:
    enabled: true
  persistence:
    enabled: true
    existingClaim: pocket-id
    extraVolumeMounts:
      - name: postgres-certs
        mountPath: /var/run/secrets/postgresql
        readOnly: true
      - name: postgres-server-ca
        mountPath: /var/run/secrets/postgres-server-ca
        readOnly: true
  podTemplate:
    spec:
      volumes:
        - name: postgres-certs
          secret:
            defaultMode: 0o600
            secretName: postgres-pocket-id-cert
        - name: postgres-server-ca
          secret:
            defaultMode: 0o440
            secretName: postgres-server-ca
  route:
    enabled: true
    parentRefs:
      - name: external-gateway
        namespace: network
