---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${PG_APP:=${APP}}-postgres
spec:
  dataFrom:
    - extract:
        key: postgres-artemis
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ${PG_APP:=${APP}}-postgres
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: postgres-rw.database.svc
        POSTGRES_PORT: "5432"
        POSTGRES_DATABASE: ${PG_APP:=${APP}}
        POSTGRES_USERNAME: ${DATABASE_OWNER:=${PG_APP:=${APP}}}
        POSTGRES_PASSWORD: "{{ .password }}"
        url: "postgresql://${DATABASE_OWNER:=${PG_APP:=${APP}}}:{{ .password }}@postgres-rw.database.svc:5432/${PG_APP:=${APP}}?sslmode=verify-full&sslrootcert=/var/run/secrets/postgres-server-ca/ca.crt"
        url_node: "postgresql://${DATABASE_OWNER:=${PG_APP:=${APP}}}:{{ .password }}@postgres-rw.database.svc:5432/${PG_APP:=${APP}}?sslmode=verify-full"
        url_prisma: "postgresql://${DATABASE_OWNER:=${PG_APP:=${APP}}}:{{ .password }}@postgres-rw.database.svc:5432/${PG_APP:=${APP}}?sslmode=verify-full&sslcert=/var/run/secrets/postgres-server-ca/ca.crt"
