---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaizoku
spec:
  chartRef:
    kind: OCIRepository
    name: kaizoku
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      kaizoku:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/maxpiva/rensaio
              tag: latest@sha256:81f8b0f5608c7557aae25ca56db7a81fa2c645c4268cf364c3c59a9554ed534a
            env:
              PGID: 100
              PUID: 99
              RENSAIO_DATADIR: /config
              UMASK: "022"
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 2Gi
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      media:
        type: nfs
        path: /mnt/atlas/media
        server: 10.10.99.100
        advancedMounts:
          kaizoku:
            app:
              - path: /series
                subPath: downloads/kaizoku
      tmp:
        type: emptyDir
        advancedMounts:
          kaizoku:
            app:
              - path: /tmp
                subPath: tmp
      backups:
        type: emptyDir
        advancedMounts:
          kaizoku:
            app:
              - path: /config/Backups
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
    service:
      app:
        ports:
          http:
            port: 9833
