---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaizoku
spec:
  chartRef:
    kind: OCIRepository
    name: kaizoku
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 100
        runAsNonRoot: true
        runAsUser: 99
    controllers:
      kaizoku:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/maxpiva/kaizoku-net
              tag: 2.0@sha256:7ed5b2375155b2bee9625f86e4c046779882dcefb3a74b924c92e04bdb69b549
            env:
              PGID: 100
              PUID: 99
              UMASK: "022"
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      media:
        type: nfs
        path: /mnt/atlas/media
        server: 10.10.99.100
        advancedMounts:
          kaizoku:
            app:
              - path: /series
                subPath: downloads/kaizoku
      tmp:
        type: emptyDir
        advancedMounts:
          kaizoku:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
    service:
      app:
        ports:
          http:
            port: 9833
