# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: qwen3-embedding
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 8083
      appProtocol: http
