---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-tunnel
spec:
  data:
    - secretKey: FROSTLINK_TUNNEL_ID
      remoteRef:
        key: cloudflare-frostlink
        property: CLOUDFLARE_TUNNEL_ID
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-dns-tunnel-secret
