---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgesync
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgesync-secret
    creationPolicy: Owner
    template:
      data:
        FORGESYNC_SOURCE_TOKEN: "{{ .FORGE_SYNC_SOURCE_TOKEN }}"
        FORGESYNC_GITHUB_TOKEN: "{{ .GITHUB_PAT }}"
  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: github
