---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgesync
spec:
  chartRef:
    kind: OCIRepository
    name: forgesync
  interval: 30m
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: forgejo-registry-pull
    controllers:
      forgesync:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
        containers:
          app:
            image:
              repository: git.dcunha.io/exikle/forgesync
              tag: 0.0.4@sha256:e65978b1d597607b36797446ea50881725f0b32ac3f2bc65623bbeb75b2dac4d
            args:
              - run
            env:
              FORGESYNC_SOURCE_URL: http://forgejo.external-endpoints.svc.cluster.local:3000
              FORGESYNC_BOT_USERNAME: exikle
              FORGESYNC_LOG_FORMAT: json
            envFrom:
              - secretRef:
                  name: forgesync-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
                  initialDelaySeconds: 5
                  periodSeconds: 30
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    externalSecrets:
      env:
        refreshInterval: 5m
        dataFrom:
          - extract:
              key: forgejo
          - extract:
              key: github
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-connect
        target:
          name: forgesync-secret
          template:
            data:
              FORGESYNC_SOURCE_TOKEN: "{{ .FORGEJO_PAT }}"
              FORGESYNC_GITHUB_TOKEN: "{{ .GITHUB_PAT }}"
