---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pelican
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pelican-secret
    template:
      engineVersion: v2
      data:
        APP_KEY: "{{ .APP_KEY }}"
        APP_URL: "https://pelican.dcunha.io"
        OAUTH_POCKETID_BASE_URL: "https://auth.dcunha.io"
        OAUTH_POCKETID_CLIENT_ID: "{{ .OAUTH_POCKETID_CLIENT_ID }}"
        OAUTH_POCKETID_CLIENT_SECRET: "{{ .OAUTH_POCKETID_CLIENT_SECRET }}"
        OAUTH_POCKETID_DISPLAY_NAME: "PocketID"
        OAUTH_POCKETID_SHOULD_CREATE_MISSING_USERS: "true"
        OAUTH_POCKETID_SHOULD_LINK_MISSING_USERS: "true"
  dataFrom:
    - extract:
        key: pelican
