---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: paperless
spec:
  allowRepeat: true
  length: 64
  noUpper: false
  secretKeys:
    - PAPERLESS_SECRET_KEY
  symbols: 0
