---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname paperless
spec:
  dataFrom:
    - extract:
        key: paperless
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      data:
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {"openid_connect": {"EMAIL_AUTHENTICATION": true, "APPS": [{"provider_id": "pocket-id", "name": "Pocket-ID", "client_id": "paperless", "secret": "{{ .PAPERLESS_OIDC_CLIENT_SECRET }}", "settings": {"server_url": "https://auth.dcunha.io"}}]}}
      engineVersion: v2
