---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gatus-remote-reader-token
  annotations:
    kubernetes.io/service-account.name: gatus-remote-reader
type: kubernetes.io/service-account-token
