[real_ip]
x_for = 1
ipv4_prefix = 32
ipv6_prefix = 48
link_local = true

[botdetection.ip_limit]
link_token = true

[botdetection.ip_lists]
pass_ip = [
  "10.0.0.0/8",
  "192.168.0.0/16",
]
block_ip = []
