[botdetection.trusted_proxies]
values = [
  "10.0.0.0/8",
  "192.168.0.0/16",
]

[botdetection.ip_limit]
link_token = false

[botdetection.ip_lists]
pass_ip = [
  "10.0.0.0/8",
  "192.168.0.0/16",
]
block_ip = []
