---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname streamystats
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        POSTGRES_PASSWORD: "{{ .STREAMYSTATS_POSTGRES_PASSWORD }}"
        SESSION_SECRET: "{{ .STREAMYSTATS_SESSION_SECRET }}"
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: "{{ .STREAMYSTATS_ENCRYPTION_KEY }}"
        DATABASE_URL: "postgresql://postgres:{{ .STREAMYSTATS_POSTGRES_PASSWORD }}@streamystats-vectorchord:5432/streamystats"
  dataFrom:
    - extract:
        key: streamystats
