---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname autopulse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        autopulse-username: "{{ .AUTOPULSE_USERNAME }}"
        autopulse-password: "{{ .AUTOPULSE_PASSWORD }}"
        jellyfin-token: "{{ .AUTOPULSE_JELLYFIN_TOKEN }}"
  dataFrom:
    - extract:
        key: autopulse
