---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autopulse
spec:
  chartRef:
    kind: OCIRepository
    name: autopulse
  interval: 1h
  values:
    controllers:
      autopulse:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dan-online/autopulse
              tag: v1.6.0
            env:
              AUTOPULSE__TARGETS__JELLYFIN__TOKEN__FILE: /autopulse-secrets/jellyfin-token
              AUTOPULSE__AUTH__USERNAME__FILE: /autopulse-secrets/autopulse-username
              AUTOPULSE__AUTH__PASSWORD__FILE: /autopulse-secrets/autopulse-password
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 2875
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
          ui:
            image:
              repository: ghcr.io/dan-online/autopulse
              tag: ui
            env:
              FORCE_AUTH: "true"
              FORCE_SERVER_URL: http://localhost:2875
              ORIGIN: https://autopulse.dcunha.io
              PORT: &uiport 2885
            envFrom:
              - secretRef:
                  name: autopulse-ui
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *uiport
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *uiport
            targetPort: *uiport
          api:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *uiport
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      app-config:
        type: configMap
        name: autopulse-config
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
      secrets:
        type: secret
        name: autopulse
        globalMounts:
          - path: /autopulse-secrets
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
