---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autopulse
spec:
  chartRef:
    kind: OCIRepository
    name: autopulse
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      autopulse:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dan-online/autopulse
              tag: v2.0.0@sha256:a9b37936c849b34d3473caf7d83aeddc2c39ec066e18a14a0f4164846d1e4718
            env:
              AUTOPULSE__TARGETS__JELLYFIN__TOKEN__FILE: /autopulse-secrets/jellyfin-token
              AUTOPULSE__AUTH__USERNAME__FILE: /autopulse-secrets/autopulse-username
              AUTOPULSE__AUTH__PASSWORD__FILE: /autopulse-secrets/autopulse-password
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 2875
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
          ui:
            image:
              repository: ghcr.io/dan-online/autopulse
              tag: ui@sha256:2df63fb2ad4c23bce338741e2e8e32c481fe39a603810ba3b6f441e406173e20
            env:
              FORCE_AUTH: "true"
              FORCE_SERVER_URL: http://localhost:2875
              ORIGIN: https://autopulse.dcunha.io
              PORT: &uiport 2885
            envFrom:
              - secretRef:
                  name: autopulse-ui
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *uiport
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      app-config:
        type: configMap
        name: autopulse-config
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
      secrets:
        type: secret
        name: autopulse
        globalMounts:
          - path: /autopulse-secrets
            readOnly: true
      tmp:
        type: emptyDir
        advancedMounts:
          autopulse:
            app:
              - path: /tmp
                subPath: tmp
            ui:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *uiport
    service:
      app:
        ports:
          http:
            port: *uiport
            targetPort: *uiport
          api:
            port: *port
