---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/refs/tags/v8.7.2/schemas/config-schema.json
sonarr:
  series:
    base_url: http://sonarr.media.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      episodes:
        anime: default
        daily: default
        rename: true
        standard: default
      season: default
      series: plex-imdb
    quality_definition:
      type: series
    quality_profiles:
      - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
        name: Standard TV
        reset_unmatched_scores:
          enabled: true
      - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
        name: K-Drama
        reset_unmatched_scores:
          enabled: true
      - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
        name: C-Drama
        reset_unmatched_scores:
          enabled: true
      - trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
        name: Anime
        reset_unmatched_scores:
          enabled: true
    custom_format_groups:
      add:
        - trash_id: 35fb4585dcd9e2a5ac732e4309f5a45a # [Streaming Services] Asian
          assign_scores_to:
            - name: K-Drama
            - name: C-Drama
        - trash_id: dad6a8cceaa4fee536eaec55201c70c3 # [Release Groups] Asian
          assign_scores_to:
            - name: K-Drama
            - name: C-Drama
    custom_formats:
      - trash_ids:
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: Standard TV
          - name: K-Drama
          - name: C-Drama
      - trash_ids:
          - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback)
        assign_scores_to:
          - name: Standard TV
          - name: K-Drama
          - name: C-Drama
          - name: Anime
radarr:
  movies:
    base_url: http://radarr.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      folder: plex-imdb
      movie:
        rename: true
        standard: plex-imdb
    quality_definition:
      type: sqp-uhd
    quality_profiles:
      - trash_id: 5128baeb2b081b72126bc8482b2a86a0 # [SQP] SQP-1 (2160p)
        reset_unmatched_scores:
          enabled: true
      - trash_id: d1d67249d3890e49bc12e275d989a7e9 # HD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
      - trash_id: 722b624f9af1e492284c4bc842153a38 # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true
    custom_formats:
      - trash_ids:
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - trash_id: 5128baeb2b081b72126bc8482b2a86a0
          - trash_id: d1d67249d3890e49bc12e275d989a7e9
      - trash_ids:
          - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost
          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - trash_id: 5128baeb2b081b72126bc8482b2a86a0
