---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 20
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/gpu-tier
                    operator: In
                    values:
                      - arc
            - weight: 10
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/gpu-tier
                    operator: In
                    values:
                      - gen95
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        supplementalGroups:
          - 44
          - 105
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: jellyfin-gpu
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_PublishedServerUrl: https://{{ .Release.Name }}.dcunha.io
            ports:
              - containerPort: 8096
                name: http
              - containerPort: 7359
                protocol: UDP
                name: discovery
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  initialDelaySeconds: 0
                  timeoutSeconds: 10
                  periodSeconds: 10
                  failureThreshold: 60
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 30
                  failureThreshold: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 30
                  failureThreshold: 6
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 1
                memory: 2Gi
              limits:
                memory: 16Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      media:
        type: nfs
        path: /mnt/atlas/media
        server: 10.10.99.100
        globalMounts:
          - path: /media
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /tmp
                subPath: tmp
              - path: /transcode
                subPath: transcode
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: external-gateway
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8096
      frostlink:
        hostnames:
          - "{{ .Release.Name }}.frostlink.dev"
        parentRefs:
          - name: edge-gateway
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8096
    service:
      app:
        controller: jellyfin
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: 8096
