---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: jellyfin-gpu
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.8@sha256:93227545077893cc9516f28b3adb733b67bc4691f41b6167428a2a0e3220b81c
            env:
              JELLYFIN_PublishedServerUrl: https://{{ .Release.Name }}.dcunha.io
              TZ: America/Toronto
            ports:
              - containerPort: 8096
                name: http
              - containerPort: 7359
                protocol: UDP
                name: discovery
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  initialDelaySeconds: 0
                  timeoutSeconds: 10
                  # this gives us 600s (10*60) to start then liveness and readiness checks begin
                  periodSeconds: 10
                  failureThreshold: 60
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 30
                  failureThreshold: 6
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 16Gi
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/gpu
                    operator: In
                    values:
                      - "true"
            - weight: 50
              preference:
                matchExpressions:
                  - key: extensions.talos.dev/i915
                    operator: Exists
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
          - 105
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 80
            targetPort: 8096
          jellyfin:
            port: 8096
            targetPort: 8096
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: external-gateway
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 80
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      cache:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
          - path: /cache
      media:
        type: nfs
        server: 10.10.99.100
        path: /mnt/atlas/media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      transcode:
        type: emptyDir
        medium: Memory
        sizeLimit: 8Gi
        globalMounts:
          - path: /transcode
