---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-crds
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/ai/toolhive/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 1h
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: toolhive-crds
  path: ./kubernetes/apps/ai/toolhive/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 1h
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: toolhive-mcp-servers
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: toolhive-mcp-servers
  dependsOn:
    - name: toolhive
  path: ./kubernetes/apps/ai/toolhive/mcp-servers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: toolhive-config
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: toolhive-config
  dependsOn:
    - name: toolhive-mcp-servers
  path: ./kubernetes/apps/ai/toolhive/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 1h
