---
all:
  children:
    proxmox:
      hosts:
        pantheon:
          ansible_host: 10.10.99.104
    storage:
      hosts:
        atlas:
          ansible_host: 10.10.99.100
    containers:
      hosts:
        forgejo:
          ansible_host: 10.10.99.24
          ansible_user: root
    workstations:
      hosts:
        grimoire:
          ansible_host: 10.10.1.157
    network:
      hosts:
        crs309:
          ansible_host: 172.16.99.2
          ansible_connection: ansible.netcommon.network_cli
          ansible_network_os: community.routeros.routeros
