---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: forgejo
  labels:
    kubernetes.io/service-name: forgejo
addressType: IPv4
endpoints:
  - addresses:
      - 10.10.99.24
    conditions:
      ready: true
      serving: true
      terminating: false
ports:
  - name: http
    port: 3000
    protocol: TCP
    appProtocol: http
