apiVersion: v1
kind: Service
metadata:
  name: &app forgejo
  annotations:
    gatus.home-operations.com/enabled: "true"
    gatus.home-operations.com/endpoint: |-
      url: "https://git.dcunha.io"
      group: homelab
      interval: 1m
      ui:
        hide-hostname: true
        hide-url: true
      conditions:
        - "[STATUS] == 200"
spec:
  clusterIP: None
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
      appProtocol: http
