---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
spec:
  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: dusk-bot
    - extract:
        key: github
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
    template:
      data:
        RENOVATE_GITHUB_COM_TOKEN: "{{ .GITHUB_PAT }}"
        RENOVATE_TOKEN: "{{ .DUSK_BOT_PAT }}"
        RENOVATE_WEBHOOK_TOKEN: "{{ .RENOVATE_WEBHOOK_TOKEN }}"
      engineVersion: v2
