---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: artemis-cluster
spec:
  extraEnv:
    - name: RENOVATE_BRANCH_PREFIX
      value: "renovate-"
    - name: RENOVATE_GIT_AUTHOR
      value: "dusk-bot <171887436+dusk-bot[bot]@users.noreply.github.com>"
    - name: RENOVATE_HOST_RULES
      value: '[{"matchHost":"https://git.dcunha.io/","allowInternal":true},{"matchHost":"https://registry.dcunha.io/","allowInternal":true}]'
    - name: LOG_LEVEL
      value: debug
  image: ghcr.io/renovatebot/renovate:44.103.5@sha256:6bb416907b8c287328364f7c80950bde28fffbc4cf5a9f47084e92e2c92cdbe5
  parallelism: 1
  provider:
    name: forgejo
    endpoint: https://git.dcunha.io/api/v1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-secret
        key: RENOVATE_WEBHOOK_TOKEN
