---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: artemis-cluster
spec:
  provider:
    name: forgejo
    endpoint: https://git.dcunha.io/api/v1
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
  image: ghcr.io/renovatebot/renovate:43.101.1
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-secret
        key: RENOVATE_WEBHOOK_TOKEN
