---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: artemis-cluster
spec:
  extraEnv:
    - name: RENOVATE_BRANCH_PREFIX
      value: "renovate-"
    - name: RENOVATE_GIT_AUTHOR
      value: "dusk-bot <171887436+dusk-bot[bot]@users.noreply.github.com>"
    - name: LOG_LEVEL
      value: debug
  image: ghcr.io/renovatebot/renovate:44.57.0@sha256:323919dd33ef62f25216a1d35e41518774eb1c855f1ddb3a1f21e14748d83011
  parallelism: 1
  provider:
    name: forgejo
    endpoint: https://git.dcunha.io/api/v1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-secret
        key: RENOVATE_WEBHOOK_TOKEN
