---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frostlink-dev-tls
spec:
  dataFrom:
    - extract:
        key: frostlink-dev-tls
        decodingStrategy: Base64
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frostlink-dev-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: '{{ index . "tls.crt" }}'
        tls.key: '{{ index . "tls.key" }}'
