app:
  hostname: 0.0.0.0
  port: 2875

opts:
  check_path: false

triggers:
  sonarr:
    type: sonarr
  radarr:
    type: radarr

targets:
  jellyfin:
    type: jellyfin
    url: http://jellyfin.media.svc.cluster.local:8096
