---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-operator
spec:
  chartRef:
    kind: OCIRepository
    name: tekton-operator
  interval: 1h
  values:
    installCRDs: true
    operator:
      autoInstallComponents: false
      defaultTargetNamespace: tekton-system
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
      fsGroupChangePolicy: OnRootMismatch
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities: { drop: ["ALL"] }
    service:
      createServiceMonitor: true
