---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.tekton.dev/tektonconfig_v1alpha1.json
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  targetNamespace: tekton-system
  profile: all
  chain:
    disabled: true
  platforms:
    kubernetes:
      pipelinesAsCode:
        enable: false
  pipeline:
    default-affinity-assistant-pod-template: |
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/gpu-tier
                    operator: NotIn
                    values:
                      - arc
              - matchExpressions:
                  - key: node.kubernetes.io/gpu-tier
                    operator: DoesNotExist
  pruner:
    disabled: false
    schedule: "*/15 * * * *"
    resources:
      - taskrun
      - pipelinerun
    keep: 20
  result:
    disabled: true
