---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
      - name: NODE
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:95028d7822019f271ecdf63f2f1ad86c0070fef838a0586c1c24e985219c6e41
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 256Mi
    volumeMounts:
      - mountPath: /var/run/secrets/talos.dev
        name: talos
        readOnly: true
volumes:
  - name: talos
    secret:
      secretName: forgejo-runner-talos
restartPolicy: Never
