---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:a734c9ce7102d891f33cd9b64497255626df1a976179e73befe9851d5659cf6b
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 256Mi
restartPolicy: Never
