---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
      - name: NODE
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:0e2ed281edc17bb61bac87c562707b2408cc75309feb7a893edf9d36b3677d1a
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 256Mi
    volumeMounts:
      - mountPath: /var/run/secrets/talos.dev
        name: talos
        readOnly: true
volumes:
  - name: talos
    secret:
      secretName: forgejo-runner-talos
restartPolicy: Never
