---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:0e2ed281edc17bb61bac87c562707b2408cc75309feb7a893edf9d36b3677d1a
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 256Mi
restartPolicy: Never
