---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
      - name: NODE
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:fce99eeccdfec1780643510c72d8fcbb8ef5fa82a54066ed4aaab3d03a3eb830
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 256Mi
    volumeMounts:
      - mountPath: /var/run/secrets/talos.dev
        name: talos
        readOnly: true
volumes:
  - name: talos
    secret:
      secretName: forgejo-runner-talos
restartPolicy: Never
