---
cache:
  enabled: true
  dir: /data/cache
container:
  docker_host: "-"
  workdir_parent: shared/workdir
host:
  workdir_parent: /data/act
kubernetes:
  namespace: forgejo
  poll_timeout: 10m
log:
  level: info
plugins:
  k8s:
    address: "unix:///plugin/forgejo-runner-k8s.sock"
    options:
      namespace: forgejo
      poll_timeout: 10m
runner:
  capacity: 4
  labels:
    - ubuntu-latest:k8s:/config/podspec-default.yaml
    - ubuntu-24.04:k8s:/config/podspec-default.yaml
    - default:k8s:/config/podspec-default.yaml
    - docker:k8s:/config/podspec-dind.yaml
    - multiarch:k8s:/config/podspec-dind.yaml
    - talos:k8s:/config/podspec-talos.yaml
  timeout: 3h
