apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: ha-google-assistant
    namespace: artemis-cluster
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: bitwarden-cluster-store
        kind: ClusterSecretStore
    target:
        name: ha-google-assistant
        deletionPolicy: Delete
    dataFrom:
        - extract:
            key: ENC[AES256_GCM,data:DJgBxXPuah5h/QMYlI2ZuDYdkyNNJxxYqMz9NEzmsCeGtDEW,iv:3SeniuOitJIrp6hLahQ4agifBmaFJ7ZE2VHRwP/JNjo=,tag:KpbnO4C/CkQxSRqAN73jPQ==,type:str]
            decodingStrategy: None
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c0pswh5sdp70kxpanshda58ulx5zhyaat7gzqg597alw4la8d9us8ykqa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QU00WXVrVkd3Y0c5NWZk
            SUIyZHJFVDVhSXVUcHNwRDJub1VWTDNBVTBjCklEUUpmVm4yUGJWblNWMGg1Z1Zm
            QWsycSt4d2RISGdPdU53b1lDWGEzN2MKLS0tIHdORjVMTnB1cTlLeVQwNU53M1Bm
            UFIvQnZxNEdET0ViQ1NNQkdwUzJldlEK9pn5OIjCXchIeRfYDf4tqE5L4AOqAAr2
            VYTeCzlG7tSPFhN/kft9rnkfLohe5/1ql4acuPgkPZt3BCLn0GMkCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T08:09:04Z"
    mac: ENC[AES256_GCM,data:NxXmyIAIe8dN2sUSQcc/4+5cDzJ+dxrrmj9a08sw1DwbRitDA5cP950wFhn/wh+borXbfrj4EnTzWDth6gpODPnqHKl8V4wles/TS2ttlgYEC0L5OCmm2btbnnEuTma3+M4OM6BiQ+Mse+gGvMbpePhtId24E7YZnjV6lzji2D4=,iv:3HzkgW3wuy8vgFb6ecI3aH/bTNlE+x6lXYRO99U34nI=,tag:Lj8dtR43QHmuseIrEP+vHg==,type:str]
    pgp: []
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    version: 3.8.1
