apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: ha-govee
    namespace: artemis-cluster
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: bitwarden-cluster-store
        kind: ClusterSecretStore
    target:
        name: ha-govee
        deletionPolicy: Delete
    dataFrom:
        - extract:
            key: ENC[AES256_GCM,data:OEyU5Ter/rYMqykeQh1IPJ//6y+ZK2TbV14m1gc9Urj3I2jM,iv:BesE8G45Phr/BTyjB8yEYJ2aBLKd52RDX+MF4lTM1Wk=,tag:05FlE4phTjf641H/Ouj5fg==,type:str]
            decodingStrategy: None
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c0pswh5sdp70kxpanshda58ulx5zhyaat7gzqg597alw4la8d9us8ykqa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOHJpQkI4QjZjVTNWT3NH
            TXkxU1JpWDJyWm9OUmR5RjNFUTc4dnVJR2lVCll3TFJFR1R4OFRPNFNrSnhKYWxH
            VkU5N0N2aERheXVKNElyNE9Xd0tyUVUKLS0tIFpJS0ZMT2duWk9HOTFXKytzRTdk
            dG15T0hUN1VCU29PWnRjUWxKQlREdVkKnUNgjRTFJmVvVRtwW2fWa+85XBnh8p5Z
            rgPG1ixobQSoXsD/gSLxqu9rwEutjRU2XYgWiqPTmO8K+TKtBu1DFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T08:08:58Z"
    mac: ENC[AES256_GCM,data:ucJlL1opPlqPBJrG88ZqSr8BRpavzFygC1owTLZpdRrK439rNOg/2uJrw9R+aYGAdjXe/v/Cz30osmyApbZVQsray9R94A/w45CD4FBuA2Jq9KGFdLJLeyh1/W75EkMgBUXOp0rCorFO6vIBzmeOQbpbOX/cPruVL3Q2eIVMs/U=,iv:8dvBV2JWbielzzx8MlASkOI13YsqLc9npNHvHfxxkuY=,tag:4Sbi4NVOmyb3seROuEYz/g==,type:str]
    pgp: []
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    version: 3.8.1
