apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: ha-google-service-account
    namespace: artemis-cluster
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: bitwarden-cluster-store
        kind: ClusterSecretStore
    target:
        name: ha-google-service-account
        deletionPolicy: Delete
    dataFrom:
        - extract:
            key: ENC[AES256_GCM,data:PcaSB91jUWqdJDffKe6xZsTc/KaV83jz9Leb65REiEH7Tuwd,iv:dBcMNU1o+vYdvEqHudJsW3nBt8ZqYrOiDELLf2o7EqI=,tag:Pp9wXKmQkA2EtDrGVh75jQ==,type:str]
            decodingStrategy: None
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c0pswh5sdp70kxpanshda58ulx5zhyaat7gzqg597alw4la8d9us8ykqa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVFU1TXRZbUxRd3JpbGNh
            bUkrWk5ITEhlUndSM0JhRDhMOGF3RVZYVERnCnU4ZVVQTm1ub3MzdzZiNlkvcTli
            WDFVQ3ZybkVHRG5MUGpqTlNoV0hQVWMKLS0tIDAyWktiM1dnRnlBQk9KckJkVGdJ
            KzN5UllVZ0JJNjJIVDlLaE93MFl6bUUKzAjKm7uCk3HqcminhyiBoPnNpkofqkqE
            qqKRI3kuieUS3MKaI3D0srI3V6fJywrXeSVQXN8aAhrYYoqgaMxsAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T08:09:10Z"
    mac: ENC[AES256_GCM,data:dT2ctYeoJX6g2vfzc8n7gu3RVq7jQm+5zDpvdb/1jrpa5tptvdP24twDuunQ6sjQW2F3H+DIWWec8Lp+acW30vQ7CSsBqyCDELHR/1BmDYqp+xSar2T3AGsqwRJZYhtXcYTxRHf1Ri4cQ6ZInx0/pM/WBbMmO8CmGkIi0xPd3eM=,iv:ZcYTFFskT7wSxA3VNftNJBpJn6fQeYXSuJfHcGwaerY=,tag:Q8iQLMFWatTclAiDF4LuiA==,type:str]
    pgp: []
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    version: 3.8.1
