apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: ha-leviton
    namespace: artemis-cluster
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: bitwarden-cluster-store
        kind: ClusterSecretStore
    target:
        name: ha-leviton
        deletionPolicy: Delete
    dataFrom:
        - extract:
            key: ENC[AES256_GCM,data:JP9/cedTjZINJK0Q73u3r0CZV23Z5KuSUbOHHDUGB8FJH7h3,iv:L3S1lvpW8I629kazX4QTGkC9aZpCU8MhAczb30Xh6A4=,tag:LlqR4xZ4e8+FfBgkRoMsjw==,type:str]
            decodingStrategy: None
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c0pswh5sdp70kxpanshda58ulx5zhyaat7gzqg597alw4la8d9us8ykqa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsY2duZ0NiSkpyZmZRUzda
            SzBqMkNlZmpSSER3VE9xbkhzMnMzbDFIT1c4CmNEWDV6anRFcGQ5Q3IvNFlOb2Z6
            c2k4aTM2WVZTVVVYekhtQWZkTVEvQUEKLS0tIEN3clZuWHpENnFMaEJqUXBhWFR3
            YnhQWDRQVDlxQmNjUys4ZFZrc0lYODQKyhaX7/GBvJh4gwfuiA6QMgNwhee7swtZ
            47QqGciwfRWm0Cj28dg8rHYR3oqgFi8qGMSPMNq8kFTx1SwGV5qDgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T08:08:47Z"
    mac: ENC[AES256_GCM,data:S9Wug4Ef9EP910cfBdi7CvX2Fclh3kJ3ay4aYyjtyr96A+cXZPs5APl9x5G/zwiSdNQrRYD3DlKIiMTtwvTQ8EMxNK+9Ch53kxqB8II2FSYXQQk7MaLA//MPdmdfWZbr/bTm67WxIunBBOxBrGhxLc8YzJAOvzljnFQei224BKg=,iv:7w05oAkS2LReFzThl2TS6PSi8OqdBj0IWzujdHk1dv0=,tag:5Ro3PyfHXzMM1sCOw5YCqg==,type:str]
    pgp: []
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    version: 3.8.1
