---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
spec:
  chartRef:
    kind: OCIRepository
    name: audiobookshelf
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      audiobookshelf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.36.1@sha256:3528a93b6442ffe54bd46771bbbab7c97084e1101071586d9dc2254f30bb4358
            env:
              CONFIG_PATH: /config
              METADATA_PATH: /config/metadata
              PORT: &port 13378
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthcheck
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthcheck
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthcheck
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  failureThreshold: 30
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
          abs-tract:
            image:
              repository: docker.io/arranhs/abs-tract
              tag: v0.2.0@sha256:227a17ace1461e263f0f151c4abd635ddd96c8a6276acca9a6921da0d4ec0cba
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &absTractPort 5555
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *absTractPort
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      media:
        type: nfs
        path: /mnt/atlas/media
        server: 10.10.99.100
        globalMounts:
          - path: /audiobooks
            subPath: audiobooks
      tmpfs:
        type: emptyDir
        advancedMounts:
          audiobookshelf:
            app:
              - path: /.npm
                subPath: npm
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "audiobooks.dcunha.io"
        parentRefs:
          - name: external-gateway
            namespace: network
        rules:
          - matches:
              - path:
                  type: Exact
                  value: /login
                method: GET
              - path:
                  type: Exact
                  value: /login/
                method: GET
            filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /audiobookshelf/login/
                  statusCode: 302
          - backendRefs:
              - identifier: app
                port: *port
    service:
      abs-tract:
        controller: audiobookshelf
        ports:
          http:
            port: *absTractPort
      app:
        ports:
          http:
            port: *port
