---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-clustermesh-ca
spec:
  data:
    - secretKey: crt
      remoteRef:
        key: cilium-clustermesh-ca
        property: ca.crt
    - secretKey: key
      remoteRef:
        key: cilium-clustermesh-ca
        property: ca.key
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cilium-clustermesh-ca
    template:
      engineVersion: v2
      data:
        ca.crt: "{{ .crt | b64enc }}"
        ca.key: "{{ .key | b64enc }}"
