---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./httproute.yaml
  - ./litellmmodels.yaml
  - ./litellmproxy.yaml
  - ./networkpolicy.yaml
  - ./pgbouncer.yaml
  - ./resourceset-virtualkeys.yaml
  - ./securitypolicy.yaml
  - ./servicemonitor.yaml
  - ./virtualkey-inputs.yaml
configMapGenerator:
  - name: litellm-pgbouncer
    files:
      - pgbouncer.ini=./resources/pgbouncer.ini
      - userlist.txt=./resources/userlist.txt
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
