---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: text-embeddings-inference
spec:
  chartRef:
    kind: OCIRepository
    name: text-embeddings-inference
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    controllers:
      text-embeddings-inference:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/huggingface/text-embeddings-inference
              tag: cpu-latest@sha256:492506e6a76ce6d0fd834a49f69bee4134f5b37de06052519d358a3d5387434d
            args:
              - --model-id
              - sentence-transformers/all-MiniLM-L6-v2
              - --port
              - "8080"
              - --hostname
              - 0.0.0.0
              - --huggingface-hub-cache
              - /data
              - --auto-truncate
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  failureThreshold: 3
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  failureThreshold: 3
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  failureThreshold: 30
                  periodSeconds: 5
                  timeoutSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: "2"
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      app:
        controller: text-embeddings-inference
        ports:
          http:
            port: 8080
            protocol: TCP
