---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ${PG_APP}-db
  namespace: &namespace database
spec:
  targetNamespace: *namespace
  path: ./kubernetes/components/postgres/base/database
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
  postBuild:
    substitute:
      APP: ${PG_APP}
      OWNER: ${DATABASE_OWNER:=${PG_APP}}
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      name: postgres-${PG_APP}
      namespace: *namespace
