---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 300
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent-libtorrentv1
              tag: 5.2.1@sha256:844555b6c1ed43afcb0001100973676fc6d825d5142c65f612a25fd9eba0bb0a
            env:
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 31288
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 5
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        path: /mnt/atlas/media
        server: 10.10.99.100
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        ports:
          http:
            port: *port
        primary: true
      bittorrent:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.10.99.95
        externalTrafficPolicy: Local
        ports:
          bittorrent-tcp:
            port: *torrentPort
            protocol: TCP
