---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmproxy_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMProxy
metadata:
  name: litellm
  annotations:
    postgres.dcunha.io/skip-cert-patch: "prisma-has-no-sslkey"
spec:
  image: ghcr.io/berriai/litellm:v1.98.0@sha256:20b5044b619055374061a6d5b7b08754cad75aeabbf82ddf4f69cc0cf80ddaf4
  apiAccess:
    masterKeyRef:
      name: litellm
      key: LITELLM_MASTER_KEY
  callbacks:
    callbacks:
      - prometheus
  env:
    - name: DATABASE_URL
      value: postgresql://litellm@litellm-pgbouncer.cortex.svc.cluster.local:5432/litellm?sslmode=disable
    - name: REDIS_HOST
      value: dragonfly.database.svc.cluster.local
    - name: REDIS_PORT
      value: "6379"
    - name: LITELLM_MASTER_KEY
      valueFrom:
        secretKeyRef:
          name: litellm
          key: LITELLM_MASTER_KEY
  generalSettings:
    database_url: os.environ/DATABASE_URL
  livenessProbe:
    httpGet:
      path: /health/liveliness
      port: 4000
    initialDelaySeconds: 60
  readinessProbe:
    httpGet:
      path: /health/readiness
      port: 4000
    initialDelaySeconds: 60
  resources:
    requests:
      cpu: 25m
      memory: 512Mi
    limits:
      memory: 2Gi
  routerSettings:
    redis_host: os.environ/REDIS_HOST
    redis_port: os.environ/REDIS_PORT
  service:
    type: ClusterIP
    port: 4000
