---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: shelfmark
spec:
  allowedUserGroups:
    - name: app-users
      namespace: security
  callbackUrls:
    - "https://booksearch.dcunha.io/api/auth/oidc/callback"
  clientID: shelfmark
  launchUrl: "https://booksearch.dcunha.io"
  logo:
    autoGenerate: false
  pkceEnabled: true
  secret:
    storeClientSecret: true
