---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  chartRef:
    kind: OCIRepository
    name: recyclarr
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      recyclarr:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          backoffLimit: 0
          schedule: 0 0 * * *
          ttlSecondsAfterFinished: 86400
        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.7.3@sha256:9c6c74d52cfc6f740a5a3624aa83867e171bb70b90453ddb7a4048b8c80445f9
            args:
              - sync
            envFrom:
              - externalSecretRef:
                  identifier: env
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 384Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    externalSecrets:
      env:
        dataFrom:
          - extract:
              key: radarr
          - extract:
              key: sonarr
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-connect
        target:
          template:
            data:
              RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
              SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
    persistence:
      config:
        type: emptyDir
      config-file:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
      tmp:
        type: emptyDir
        advancedMounts:
          recyclarr:
            app:
              - path: /tmp
                subPath: tmp
