---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-secrets
    template:
      engineVersion: v2
      data:
        secrets.yaml: |
          wifi_ssid: "{{ .WIFI_SSID }}"
          wifi_password: "{{ .WIFI_PASSWORD }}"
          api_encryption_key: "{{ .API_ENCRYPTION_KEY }}"
          ota_password: "{{ .OTA_PASSWORD }}"
          fallback_hotspot_password: "{{ .FALLBACK_HOTSPOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: esphome
