---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
spec:
  chartRef:
    kind: OCIRepository
    name: esphome
  interval: 1h
  values:
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "iot",
            "namespace": "kube-system",
            "ips": [
              "10.10.152.13/24",
              "fd00:10:10:152::13/64"
            ],
            "mac": "02:4d:60:0e:5e:0d"
          }]
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      esphome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/esphome
              tag: 2026.6.2@sha256:ee7310d474219cfeee7d29ae375e31d95f47bb96c25ee6d0383c6f23e41bb43d
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 5m
                memory: 512Mi
              limits:
                memory: 3Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      secrets:
        type: secret
        name: esphome-secrets
        globalMounts:
          - path: /config/secrets.yaml
            subPath: secrets.yaml
      buildcache:
        accessMode: ReadWriteOnce
        size: 10Gi
        suffix: buildcache
        advancedMounts:
          esphome:
            app:
              - path: /cache
      tmp:
        type: emptyDir
        advancedMounts:
          esphome:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: 6052
    service:
      app:
        ports:
          http:
            port: 6052
