---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
spec:
  chartRef:
    kind: OCIRepository
    name: esphome
  interval: 1h
  values:
    controllers:
      esphome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/esphome
              tag: 2026.4.0@sha256:f2903ef91562cd00ff7707cfff417565879ad4a147a27343bc9f4be1bfe849cd
            env:
              TZ: America/Toronto
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 5m
                memory: 512Mi
              limits:
                memory: 3Gi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "iot",
            "namespace": "kube-system",
            "ips": [
              "10.10.152.13/24",
              "fd00:10:10:152::13/64"
            ],
            "mac": "02:4d:60:0e:5e:0d"
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 6052
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: 6052
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      secrets:
        type: secret
        name: esphome-secrets
        globalMounts:
          - path: /config/secrets.yaml
            subPath: secrets.yaml
      buildcache:
        suffix: buildcache
        size: 10Gi
        accessMode: ReadWriteOnce
        advancedMounts:
          esphome:
            app:
              - path: /cache
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
