---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: komga-restart
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: komga-restart
  namespace: default
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    resourceNames:
      - "komga"
    verbs:
      - "get"
      - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: komga-restart
  namespace: default
subjects:
  - kind: ServiceAccount
    name: komga-restart
    namespace: default
roleRef:
  kind: Role
  name: komga-restart
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: komga-restart
  namespace: default
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: komga-restart
          restartPolicy: OnFailure
          containers:
            - name: restart
              image: bitnami/kubectl:latest
              command:
                - kubectl
                - rollout
                - restart
                - deployment/komga
                - -n
                - default
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  memory: 64Mi
