---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: barman-r2
spec:
  dataFrom:
    - extract:
        key: cloudflare
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: barman-r2
    template:
      data:
        ACCESS_KEY_ID: "{{ .CLOUDFLARE_R2_ACCESS_TOKEN }}"
        REGION: auto
        SECRET_ACCESS_KEY: "{{ .CLOUDFLARE_R2_SECRET_ACCESS_KEY }}"
