---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dispatcharr
spec:
  chartRef:
    kind: OCIRepository
    name: dispatcharr
  interval: 1h
  values:
    controllers:
      dispatcharr:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          chown-dbdir:
            image:
              repository: docker.io/library/alpine
              tag: "3.24@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4"
            command:
              - "/bin/sh"
              - "-c"
            # CHANGED: 755 -> 750 (Strict requirement for Postgres)
            args:
              - "chmod -R 750 /data"
            securityContext:
              runAsUser: 0
        containers:
          app:
            image:
              repository: ghcr.io/dispatcharr/dispatcharr
              tag: 0.26.0@sha256:9275b0c1f5319a84b412af6839a1364ef25b61d8d6ff0d2130a6c2b2504a8b07
            env:
              DISPATCHARR_ENV: production
              DISPATCHARR_LOG_LEVEL: info
              DISPATCHARR_PORT: &port 9191
              # Redis Sidecar Connection
              REDIS_HOST: localhost
              REDIS_PORT: 6379
              REDIS_DB: 0
              CELERY_BROKER_URL: redis://localhost:6379/0
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                memory: 3Gi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        advancedMounts:
          dispatcharr:
            app:
              - path: /tmp
                subPath: tmp
