# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/discovery.k8s.io/endpointslice_v1.json
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: qwen3-reranker
  labels:
    kubernetes.io/service-name: qwen3-reranker
addressType: IPv4
endpoints:
  - addresses:
      - 10.10.99.199
    conditions:
      ready: true
      serving: true
      terminating: false
ports:
  - name: http
    port: 8082
    protocol: TCP
    appProtocol: http
