---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/trust.cert-manager.io/bundle_v1alpha1.json
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: postgres-client-ca
spec:
  sources:
    - secret:
        name: postgres-client-ca
        key: tls.crt
  target:
    secret:
      key: ca.crt
      metadata:
        labels:
          cnpg.io/reload: ""
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/trust.cert-manager.io/bundle_v1alpha1.json
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: root-ca
spec:
  sources:
    - secret:
        name: postgres-server-ca
        key: tls.crt
  target:
    secret:
      key: ca.crt
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/trust.cert-manager.io/bundle_v1alpha1.json
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: internal-ca
spec:
  sources:
    - secret:
        name: internal-ca-root-secret
        key: tls.crt
  target:
    configMap:
      key: ca.crt
