---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-database
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/database
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: onepassword-connect
      namespace: external-secrets
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-postgres-backup-target
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/postgres/backup-target
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  wait: true
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
    - name: plugin-barman-cloud
      namespace: cnpg-system
    - name: onepassword-connect
      namespace: external-secrets
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-postgres-cluster
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/postgres/cluster
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  timeout: 10m
  wait: true
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
    - name: plugin-barman-cloud
      namespace: cnpg-system
    - name: immich-postgres-backup-target
      namespace: default
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-postgres17-backup-target
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/postgres17/backup-target
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  wait: true
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
    - name: plugin-barman-cloud
      namespace: cnpg-system
    - name: onepassword-connect
      namespace: external-secrets
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-postgres17-cluster
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/postgres17/cluster
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  timeout: 10m
  wait: true
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
    - name: plugin-barman-cloud
      namespace: cnpg-system
    - name: immich-postgres17-backup-target
      namespace: default
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-postgres18-backup-target
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/postgres18/backup-target
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  wait: true
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
    - name: plugin-barman-cloud
      namespace: cnpg-system
    - name: onepassword-connect
      namespace: external-secrets
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-postgres18-cluster
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/postgres18/cluster
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  timeout: 10m
  wait: true
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
    - name: plugin-barman-cloud
      namespace: cnpg-system
    - name: immich-postgres18-backup-target
      namespace: default
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-app
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  dependsOn:
    - name: immich-database
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-microservices
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/microservices
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  dependsOn:
    - name: immich-app
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-machine-learning
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  path: ./kubernetes/apps/default/immich/machine-learning
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  timeout: 10m
  dependsOn:
    - name: immich-app
  wait: false
