---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname readarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        READARR__AUTH__APIKEY: "{{ .READARR_API_KEY }}"
  dataFrom:
    - extract:
        key: readarr
