---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: node-exporter
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: node-exporter

    extraArgs:
      - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+|etc/nfsmount\.conf)($|/)

    hostPID: true
    hostNetwork: true

    tolerations:
      - effect: NoSchedule
        operator: Exists

    resources:
      requests:
        cpu: 15m
        memory: 64Mi
      limits:
        memory: 128Mi

    prometheus:
      monitor:
        enabled: true
