---
# Source: https://github.com/ihor-sokoliuk/mcp-searxng
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  env:
    - name: MCP_HTTP_PORT
      value: ""
    - name: SEARXNG_URL
      value: http://searxng.cortex.svc.cluster.local:8080
  groupRef:
    name: artemis-general
  image: docker.io/isokoliuk/mcp-searxng:1.8.0@sha256:787626c360cc00559093416bc701bf029075615da0c67b7026e6bc11c7386f19
  proxyPort: 8080
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  transport: stdio
