---
# Source: https://github.com/ihor-sokoliuk/mcp-searxng
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  env:
    - name: MCP_HTTP_PORT
      value: ""
    - name: SEARXNG_URL
      value: http://searxng.cortex.svc.cluster.local:8080
  groupRef:
    name: artemis-general
  image: docker.io/isokoliuk/mcp-searxng:1.7.2@sha256:26cccada8604fd31f9668fe645086f647d6a415583d96b49489d2a8611909ee9
  proxyPort: 8080
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  transport: stdio
