---
# Source: https://github.com/ihor-sokoliuk/mcp-searxng
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  env:
    - name: SEARXNG_URL
      value: http://searxng.cortex.svc.cluster.local:8080
    - name: MCP_HTTP_PORT
      value: "3000"
  groupRef:
    name: artemis-general
  image: docker.io/isokoliuk/mcp-searxng:1.2.1@sha256:a86ee2d65b53750fb6379489e95ebe617db6a01da02ae23874075e8a44892af1
  mcpPort: 3000
  proxyPort: 8080
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  transport: streamable-http
