---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: icmp
spec:
  jobName: blackbox-icmp
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        # --- Talos Control Plane ---
        - 10.10.99.101 # talos-cp-01
        - 10.10.99.102 # talos-cp-02
        - 10.10.99.103 # talos-cp-03

        # --- Talos Workers ---
        - 10.10.99.201 # talos-w-01
        - 10.10.99.202 # talos-w-02
        - 10.10.99.203 # talos-gpu-01
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: tcp
spec:
  jobName: blackbox-tcp
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - truenas.external-endpoints.svc.cluster.local:2049 # TrueNAS NFS
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
