---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web-automated
spec:
  chartRef:
    kind: OCIRepository
    name: calibre-web-automated
  interval: 1h
  values:
    controllers:
      calibre-web-automated:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/crocodilestick/calibre-web-automated
              tag: v4.0.6@sha256:c31a738b6d5ec6982c050063dd3f063b6943eb1051fc81144789f840d9093a8d
            env:
              TZ: America/Toronto
              PUID: "1000"
              PGID: "1000"
              NETWORK_SHARE_MODE: "true"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 8083
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /login
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  failureThreshold: 60
            resources:
              requests:
                cpu: 15m
                memory: 256Mi
              limits:
                memory: 1Gi

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "books.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: 10.10.99.100
        path: /mnt/atlas/media
        globalMounts:
          - path: /calibre-library
            subPath: books
          - path: /cwa-book-ingest
            subPath: book-ingest
