---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname komga-exporter
spec:
  dataFrom:
    - extract:
        key: komga
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        config.yml: |
          modules:
            komga:
              headers:
                X-API-Key: "{{ .KOMGA_API_KEY }}"
              metrics:
                - name: komga_actuator
                  type: object
                  help: Spring Boot Actuator measurement scraped from Komga
                  path: '{.measurements[*]}'
                  labels:
                    statistic: '{.statistic}'
                  values:
                    value: '{.value}'
