---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: komga-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: komga-exporter
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      komga-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/prometheuscommunity/json-exporter
              tag: v0.8.0@sha256:3aad20d41a0b31dfaaf7ab1a091440e92a82a61ef68b76750eac0ad50a983652
            args:
              - --config.file=/config/config.yml
              - --log.level=warn
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: &port 7979
                  initialDelaySeconds: 5
                  periodSeconds: 30
              readiness: *probe
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      config:
        type: secret
        name: komga-exporter
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
    service:
      app:
        ports:
          http:
            port: *port
