---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pipelines
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pipelines
    template:
      data:
        MEM0_API_KEY: "{{ .MEM0_API_KEY }}"
  dataFrom:
    - extract:
        key: mem0
