---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pipelines
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pipelines
    template:
      data:
        AGENTMEMORY_SECRET: "{{ .AGENTMEMORY_SECRET }}"
  dataFrom:
    - extract:
        key: agentmemory
