---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: pipelines-config
    files:
      - agentmemory_memory_filter_pipeline.py=./resources/agentmemory_memory_filter_pipeline.py
generatorOptions:
  disableNameSuffixHash: true
