---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.networking.k8s.io/backendtlspolicy_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: pve-backend-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: pve
  validation:
    caCertificateRefs:
      - name: pve-ca-cert
        group: ""
        kind: ConfigMap
    hostname: pve.dcunha.io
