---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: atlas
spec:
  allowedNamespaces:
    all: true
  backend:
    filesystem:
      path: /repository
      volume:
        nfs:
          server: 10.10.99.100
          path: /mnt/atlas/Kopiur
  bootstrap:
    failurePolicy:
      activeDeadlineSeconds: 1800
  create:
    enabled: true
  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  health:
    indexBlobWarnThreshold: 4000
  identityDefaults:
    hostnameExpr: namespace
    usernameExpr: policyName
  maintenance:
    failurePolicy:
      activeDeadlineSeconds: 3600
    mover:
      cache:
        capacity: 10Gi
        contentCacheSizeMb: 3000
        metadataCacheSizeMb: 4000
        mode: Persistent
        storageClassName: ceph-block
    schedule:
      full:
        cron: 0 3 * * *
        jitter: 1h
      quick:
        cron: 0 * * * *
        jitter: 10m
  moverDefaults:
    cache:
      capacity: 5Gi
      contentCacheSizeMb: 2000
      metadataCacheSizeMb: 1000
      mode: Ephemeral
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
  parameters:
    epoch:
      minDuration: 6h
  scheduleDefaults:
    timezone: America/Toronto
