---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: rensaio
spec:
  allowedUserGroups:
    - name: app-users
      namespace: security
  callbackUrls:
    - "https://rensaio.dcunha.io/api/auth/oidc/callback"
  clientID: rensaio
  launchUrl: "https://rensaio.dcunha.io/"
  logo:
    autoGenerate: false
  pkceEnabled: true
  secret:
    storeClientSecret: true
