---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname unifi
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        UNIFI_API_KEY: "{{ .UNIFI_API_KEY }}"
  dataFrom:
    - extract:
        key: unifi
