---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./forgejo-runner/ks.yaml
  - ./forgesync/ks.yaml
  - ./tekton-runner/ks.yaml
