---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: bazarr
  namespace: media
spec:
  oidc:
    clientID: bazarr
    clientSecret:
      name: bazarr
    forwardAccessToken: false
    provider:
      issuer: https://auth.dcunha.io
    redirectURL: "https://bazarr.dcunha.io/oauth2/callback"
    scopes:
      - openid
      - profile
      - email
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: bazarr
