---
# Source: https://github.com/homeassistant-ai/ha-mcp
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-ha
spec:
  env:
    - name: HOMEASSISTANT_URL
      value: http://home-assistant.home-automation.svc.cluster.local:8123
  groupRef:
    name: artemis-ops
  image: ghcr.io/homeassistant-ai/ha-mcp:latest@sha256:8639b177d83bc27a74332ea83513e961fbe7e1a9504c945d979a9e0a914ffe69
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
  proxyPort: 8080
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  secrets:
    - name: ha-mcp
      key: HA_TOKEN
      targetEnvName: HOMEASSISTANT_TOKEN
  transport: stdio
