---
# Source: https://github.com/voska/hass-mcp
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-ha
spec:
  env:
    - name: HA_URL
      value: http://home-assistant.home-automation.svc.cluster.local:8123
  groupRef:
    name: artemis-ops
  image: docker.io/voska/hass-mcp:latest
  proxyPort: 8080
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  secrets:
    - name: ha-mcp
      key: HA_TOKEN
      targetEnvName: HA_TOKEN
  transport: stdio
