---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: itzg/minecraft-server
              tag: java25@sha256:d209013e65134d9c6aa0c962e81ddf1214efa733a4eec81d5d079b1b49c0a598
            env:
              ENABLE_WHITELIST: "TRUE"
              ENFORCE_WHITELIST: "TRUE"
              EULA: "TRUE"
              MEMORY: ""
              OVERRIDE_WHITELIST: "TRUE"
              TYPE: VANILLA
              VERSION: LATEST
              WHITELIST: exikle
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - mc-health
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  failureThreshold: 10
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - mc-health
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  failureThreshold: 60
            resources:
              requests:
                cpu: 250m
                memory: 1Gi
              limits:
                memory: 4Gi
          exporter:
            image:
              repository: itzg/mc-monitor
              tag: 0.17.1@sha256:f0667f713856e953dc82c70a608b986b943b33f4b65a9dd55a8ede17fe48f34e
            args:
              - export-for-prometheus
            env:
              EXPORT_PORT: "8080"
              EXPORT_SERVERS: localhost:25565
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    persistence:
      data:
        existingClaim: minecraft
        globalMounts:
          - path: /data

    service:
      app:
        controller: minecraft
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          lbipam.cilium.io/ips: 10.10.99.94
          external-dns.alpha.kubernetes.io/hostname: minecraft.dcunha.io
        ports:
          minecraft:
            port: 25565
            protocol: TCP
      metrics:
        controller: minecraft
        type: ClusterIP
        ports:
          metrics:
            port: 8080
