---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: itzg/minecraft-server
              tag: java25@sha256:8d0500eb1df76328fb2c2cd0350d5d456c1be45c7a92d6363ad35b680bdbcecf
            env:
              ENABLE_WHITELIST: "TRUE"
              ENFORCE_WHITELIST: "TRUE"
              EULA: "TRUE"
              MEMORY: ""
              OVERRIDE_WHITELIST: "TRUE"
              TYPE: VANILLA
              VERSION: LATEST
              WHITELIST: exikle
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - mc-health
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  failureThreshold: 10
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - mc-health
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  failureThreshold: 60
            resources:
              requests:
                cpu: 250m
                memory: 1Gi
              limits:
                memory: 4Gi
          exporter:
            image:
              repository: itzg/mc-monitor
              tag: 0.18.1@sha256:6e38245c074f5d15e28131657f48b41eaaac08d18a24131c545cc607345f92bb
            args:
              - export-for-prometheus
            env:
              EXPORT_PORT: "8080"
              EXPORT_SERVERS: localhost:25565
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    persistence:
      data:
        existingClaim: minecraft
        globalMounts:
          - path: /data

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.10.99.94
          external-dns.kubernetes.io/hostname: minecraft.dcunha.io
        controller: minecraft
        externalTrafficPolicy: Local
        ports:
          minecraft:
            port: 25565
      metrics:
        controller: minecraft
        ports:
          metrics:
            port: 8080
