---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qui
spec:
  chartRef:
    kind: OCIRepository
    name: qui
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      qui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/autobrr/qui
              tag: v1.18.0@sha256:2e768c8509831afd1f606d27d9aa8e5f3fc722fac4ea88acfdc4fa3b0e9b13ae
            env:
              QUI__AUTH_DISABLED: true
              QUI__AUTH_DISABLED_ALLOWED_CIDRS: 0.0.0.0/0
              QUI__HOST: 0.0.0.0
              QUI__I_ACKNOWLEDGE_THIS_IS_A_BAD_IDEA: true
              QUI__METRICS_ENABLED: true
              QUI__METRICS_HOST: 0.0.0.0
              QUI__METRICS_PORT: &metricsPort 8080
              QUI__PORT: &port 80
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        path: /mnt/atlas/media
        server: 10.10.99.100
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
        advancedMounts:
          qui:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
          metrics:
            port: *metricsPort
    serviceMonitor:
      app:
        endpoints:
          - port: metrics
