---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-oauth2-proxy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${OAUTH2_PROXY_HTTPROUTE:=${APP}}
  extAuth:
    http:
      path: /?rd=https://${APP}.dcunha.io
      headersToBackend:
        - Cookie
        - Authorization
      backendRefs:
        - group: ""
          kind: Service
          name: oauth2-proxy
          namespace: security
          port: 4180
