---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname discord-webhook
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: *secretname
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        address: "{{ .WEBHOOK_ADDRESS }}"
  dataFrom:
    - extract:
        key: discord
