---
- name: Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted
