---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chartRef:
    kind: OCIRepository
    name: open-webui
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      open-webui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.10.1 # https://github.com/open-webui/open-webui/releases
            env:
              ENABLE_OAUTH_SIGNUP: "true"
              ENABLE_OLLAMA_API: "true"
              ENABLE_RAG_WEB_SEARCH: "true"
              OAUTH_ADMIN_ROLES: "admins,infra"
              OAUTH_ALLOWED_ROLES: "admins,infra,users"
              OAUTH_CLIENT_ID: "openwebui"
              OAUTH_EMAIL_CLAIM: "email"
              OAUTH_PROVIDER_NAME: "Pocket-ID"
              OAUTH_ROLES_CLAIM: "groups"
              OAUTH_SCOPES: "openid profile email"
              OAUTH_USERNAME_CLAIM: "preferred_username"
              OLLAMA_BASE_URL: "http://ollama.dcunha.io:11434"
              OPENAI_API_BASE_URL: "http://pipelines.cortex.svc.cluster.local:9099"
              OPENAI_API_KEY: "0p3n-w3bu!"
              OPENID_PROVIDER_URL: "https://auth.dcunha.io/.well-known/openid-configuration"
              PORT: &port 8080
              RAG_WEB_SEARCH_ENGINE: "searxng"
              SEARXNG_QUERY_URL: "http://searxng.cortex.svc.cluster.local:8080/search?q=<query>&format=json"
              WEBUI_SECRET_KEY_FILE: /app/backend/data/.webui_secret_key
              WEBUI_URL: "https://chat.dcunha.io"
            envFrom:
              - secretRef:
                  name: open-webui
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 5
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
    persistence:
      data:
        existingClaim: open-webui
        globalMounts:
          - path: /app/backend/data
    route:
      app:
        hostnames:
          - "chat.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
          - name: external-gateway
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
