---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./oidcclient.yaml
configMapGenerator:
  - name: hermes-skill-cluster-health
    files:
      - skills/cluster-health/SKILL.md
    options:
      disableNameSuffixHash: true
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: hermes-skill-forgejo-pr-review
    files:
      - skills/forgejo-pr-review/SKILL.md
    options:
      disableNameSuffixHash: true
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: hermes-skill-readme-sync
    files:
      - skills/readme-sync/SKILL.md
    options:
      disableNameSuffixHash: true
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
