---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/fluxcd.controlplane.io/resourcesetinputprovider_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: hermes
  labels:
    litellm.dcunha.io/virtualkey: "true"
spec:
  type: Static
  defaultValues:
    name: hermes
    budgetDuration: 30d
    maxBudget: "20"
    maxParallelRequests: 4
    rpmLimit: 30
    models:
      - opencode-go/deepseek-v4-flash
      - opencode-go/glm-5.2
      - opencode-go/kimi-k2.6
      - opencode-go/kimi-k2.7-code
      - opencode-go/minimax-m3
      - opencode-go/mimo-v2.5
      - opencode-go/qwen3.6-plus
      - opencode-go/qwen3.7-max
