---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg18
spec:
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-pg18-credentials
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE
        - CREATE EXTENSION IF NOT EXISTS cube CASCADE
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE
        - CREATE EXTENSION IF NOT EXISTS pg_trgm CASCADE
        - CREATE EXTENSION IF NOT EXISTS unaccent CASCADE
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp" CASCADE
  enablePDB: false
  enableSuperuserAccess: true
  imageName: docker.io/tensorchord/cloudnative-vectorchord:18.4-1.1.1@sha256:9c9246cb8ba0332f7e1115def71329410657237db8ef104160a479a89c7e03a2
  instances: 1
  managed:
    roles:
      - ensure: present
        login: true
        name: immich
        passwordSecret:
          name: immich-pg18-credentials
        superuser: true
  plugins:
    - isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: immich-pg18-r2-store
  postgresql:
    parameters:
      archive_timeout: 900s
    shared_preload_libraries:
      - vchord.so
  primaryUpdateMethod: switchover
  storage:
    size: 20Gi
    storageClass: ceph-block
  walStorage:
    size: 4Gi
    storageClass: ceph-block
