---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/fluxcd.controlplane.io/resourcesetinputprovider_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: mcp-ops
  labels:
    litellm.dcunha.io/virtualkey: "true"
spec:
  type: Static
  defaultValues:
    name: mcp-ops
    maxParallelRequests: 8
    rpmLimit: 60
    models: []
