---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apoci
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        APOCI_REGISTRY_TOKEN: "{{ .REGISTRY_TOKEN }}"
        APOCI_ADMIN_TOKEN: "{{ .ADMIN_TOKEN }}"
        APOCI_DB_USER: "{{ .DB_USER }}"
        APOCI_DB_PASSWORD: "{{ .DB_PASSWORD }}"
        APOCI_DB_DSN: "postgres://{{ .DB_USER }}:{{ .DB_PASSWORD }}@localhost:5432/apoci?sslmode=disable"
  dataFrom:
    - extract:
        key: apoci
