---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apoci
spec:
  chartRef:
    kind: OCIRepository
    name: apoci
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      apoci:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-pgdata:
            image:
              repository: docker.io/library/busybox
              tag: latest
            command:
              - sh
              - -c
              - chown -R 1000:1000 /data
            securityContext:
              runAsUser: 0
        containers:
          app:
            image:
              repository: registry.erwanleboucher.dev/eleboucher/apoci
              tag: 0.0.56@sha256:dc69427322dd5931084c255097d70a1db857cfd4f3fe17a23e0d44921948b1d4
            env:
              APOCI_DATA_DIR: /data
              APOCI_DB_DSN:
                valueFrom:
                  secretKeyRef:
                    name: apoci-postgres
                    key: url
            envFrom:
              - secretRef:
                  name: apoci
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsGroup: 1000
              runAsUser: 1000

    persistence:
      data:
        existingClaim: apoci
        advancedMounts:
          apoci:
            init-pgdata:
              - path: /data
                subPath: data
            app:
              - path: /data
                subPath: data
      config:
        type: configMap
        name: apoci-config
        advancedMounts:
          apoci:
            app:
              - path: /apoci/config/apoci.yaml
                subPath: apoci.yaml
      tmpfs:
        type: emptyDir
        advancedMounts:
          apoci:
            app:
              - path: /tmp
                subPath: tmp

    route:
      app:
        annotations:
          fingerjoin.naktis.eu/webfinger: "true"
          gatus.home-operations.com/endpoint: |-
            name: apoci
        hostnames:
          - registry.dcunha.io
        parentRefs:
          - name: external-gateway
            namespace: network
          - name: internal-gateway
            namespace: network
    service:
      app:
        ports:
          http:
            port: 5000
          metrics:
            port: 9090
