---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  certificates:
    clientCASecret: postgres-client-ca
    replicationTLSSecret: postgres-replication-cert
    serverCASecret: postgres-server-ca
    serverTLSSecret: postgres-server-cert
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:4587df73024408f5b2be9b4dd6ba2ccee8c9e5dc0c9a87c274c292291cc8a68c
  instances: 2
  managed:
    roles:
      - disablePassword: true
        ensure: present
        login: true
        name: apoci
        superuser: false
      - disablePassword: true
        ensure: present
        login: true
        name: bookboss
        superuser: false
      - disablePassword: true
        ensure: present
        login: true
        name: memini
        superuser: false
      - disablePassword: true
        ensure: present
        login: true
        name: paperless
        superuser: false
      - disablePassword: true
        ensure: present
        login: true
        name: pocket-id
        superuser: false
      - disablePassword: true
        ensure: present
        login: true
        name: pooler-rw
        superuser: false
      - disablePassword: true
        ensure: present
        login: true
        name: streamystats
        superuser: false
  plugins:
    - isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: r2-store
  postgresql:
    extensions:
      - dynamic_library_path:
          - /usr/lib/postgresql/18/lib/
        extension_control_path:
          - /usr/share/postgresql/18/
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1@sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
        name: vchord
    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map
    pg_ident:
      - pooler-map pooler-rw all
    shared_preload_libraries:
      - vchord
  primaryUpdateMethod: switchover
  storage:
    size: 20Gi
    storageClass: ceph-block
