---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/pooler_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-rw
spec:
  cluster:
    name: postgres
  instances: 2
  pgbouncer:
    authQuery: "SELECT $1, NULL"
    clientCASecret:
      name: pooler-client-cert
    clientTLSSecret:
      name: pooler-server-cert
    parameters:
      auth_type: cert
      client_tls_sslmode: verify-full
      default_pool_size: "10"
      max_client_conn: "1000"
      max_db_connections: "20"
      max_prepared_statements: "200"
      reserve_pool_size: "5"
      reserve_pool_timeout: "3"
      server_tls_sslmode: verify-full
    poolMode: session
    serverCASecret:
      name: pooler-server-cert
    serverTLSSecret:
      name: pooler-client-cert
  type: rw
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &name pooler-rw
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      cnpg.io/poolerName: *name
