---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-tika
spec:
  chartRef:
    kind: OCIRepository
    name: paperless-tika
  interval: 1h
  values:
    controllers:
      tika:
        containers:
          app:
            image:
              repository: docker.io/apache/tika
              tag: latest-full
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: tika
        ports:
          http:
            port: 9998
