---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-tika
spec:
  chartRef:
    kind: OCIRepository
    name: paperless-tika
  interval: 1h
  values:
    controllers:
      tika:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: docker.io/apache/tika
              tag: 3.3.0.0-full@sha256:ed28cbbf59bc9e06eae6f99891a8e6d197cefdc278a296e30a135684e34ca320
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: tika
        ports:
          http:
            port: 9998
