---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: home-assistant
  interval: 1h
  values:
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "iot",
            "namespace": "kube-system",
            "ips": [
              "10.10.152.10/24",
              "fd00:10:10:152::10/64"
            ],
            "mac": "02:4d:60:06:55:be"
          }]
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.5.3@sha256:05dc008c0bad203ee4e0845a298e0fbbbdb7a6fedab912af782746e238b1e04a
            env:
              HASS_HTTP_TRUSTED_PROXY_1: 10.10.0.0/24
              HASS_HTTP_TRUSTED_PROXY_2: 10.42.0.0/16
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
                  # add: ["NET_RAW"]
              readOnlyRootFilesystem: true
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.118.0@sha256:4aff9947c113487113201da811564fade1af5f23038b4d683998d024eebbac92
            args:
              - "--auth"
              - "none"
              - "--user-data-dir"
              - "/config/.vscode"
              - "--extensions-dir"
              - "/config/.vscode"
              - "--port"
              - "12321"
              - "/config"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: false # code-server writes to home dirs and /tmp
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      config-cache:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
          - path: /config/.venv
      tmp:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: tmp
            codeserver:
              - path: /tmp
                subPath: tmp
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
          - hass.dcunha.io
        parentRefs:
          - name: external-gateway
            namespace: network
          - name: internal-gateway
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: 8123
      codeserver:
        hostnames:
          - "hass-code.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: 12321
    service:
      app:
        ports:
          codeserver:
            port: 12321
          http:
            port: 8123
