---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./arr
  - ./context7
  - ./forgejo
  - ./github
  - ./grafana
  - ./ha
  - ./k8s
  - ./searxng
  - ./seerr
  - ./victoria-logs
