---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: flux-operator-oidc-credentials
      valuesKey: client-secret
      targetPath: web.config.authentication.oauth2.clientSecret
  values:
    serviceMonitor:
      create: true
    web:
      config:
        baseURL: https://flux.dcunha.io
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            clientID: flux-operator
            issuerURL: https://id.dcunha.io
      httpRoute:
        enabled: true
        hostnames:
          - flux.dcunha.io
        parentRefs:
          - name: external-gateway
            namespace: network
      networkPolicy:
        create: false
