---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tekton-runner
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tekton-runner-secrets
    creationPolicy: Owner
    template:
      data:
        redis-encryption-key: "{{ .FORGEJO_TEKTON_RUNNER_REDIS_ENCRYPTION_KEY }}"
        token: "{{ .FORGEJO_TEKTON_RUNNER_TOKEN }}"
        uuid: "{{ .FORGEJO_TEKTON_RUNNER_UUID }}"
  dataFrom:
    - extract:
        key: forgejo-tekton-runner
