---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-runner
spec:
  chartRef:
    kind: OCIRepository
    name: tekton-runner
  interval: 1h
  values:
    app-template:
      controllers:
        forgejo-tekton-runner:
          replicas: 2
          strategy: RollingUpdate
          containers:
            runner:
              image:
                repository: registry.dcunha.io/jaspers.it/kariton/forgejo-tekton-runner
                tag: latest@sha256:06624d307ce1312bc979689a257b2a9e5315f5a69d5f2a0b1febf20808087047
              env:
                FORGEJO_URL: "http://forgejo.external-endpoints.svc.cluster.local:3000"
                RUNNER_CAPACITY: "6"
                RUNNER_DEFAULT_WORKSPACE_SIZE_LIMIT: 1Gi
                RUNNER_REDACTION_REGEXES: |-
                  (?i)authorization:\s*(bearer|token)\s+\S+
                  https://[^:/@\s]+:[^@\s]+@
                RUNNER_REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/4"
