---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cortex

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./agentmemory/ks.yaml
  - ./mcp
  - ./open-webui/ks.yaml
  - ./pipelines/ks.yaml
  - ./searxng/ks.yaml
  - ./text-embeddings-inference/ks.yaml
  - ./toolhive/ks.yaml
