---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/inference.llmkube.dev/model_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: qwen3-embedding-0.6b
spec:
  files:
    - Qwen3-Embedding-0.6B-Q8_0.gguf
  format: gguf
  hardware:
    accelerator: cpu
  quantization: Q8_0
  source: hf://Qwen/Qwen3-Embedding-0.6B-GGUF
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/inference.llmkube.dev/inferenceservice_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: qwen3-embedding-0.6b
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - talos-w-01
  batchSize: 2048
  contextSize: 8192
  endpoint:
    port: 8080
    type: ClusterIP
  extraArgs:
    - --alias
    - qwen3-embedding
    - --embeddings
    - --pooling
    - last
    - --threads
    - "4"
    - --threads-batch
    - "6"
    - --mmap
  # renovate: datasource=docker depName=ghcr.io/ggml-org/llama.cpp
  image: ghcr.io/ggml-org/llama.cpp:server-vulkan@sha256:ba79ce324b97ea25ac1ed5c1b8d0a3983ac49ed8020c792104d31eae60ea7a98
  mode: embedding
  modelRef: qwen3-embedding-0.6b
  parallelSlots: 1
  replicas: 1
  resources:
    cpu: "1"
    memory: 4Gi
  runtime: llamacpp
  skipModelInit: true
  uBatchSize: 2048
