---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: ceph-csi-drivers
      version: "1.0.1"
      sourceRef:
        kind: HelmRepository
        name: ceph-csi-operator
        namespace: rook-ceph
  interval: 1h
  values:
    cephConnections: []
    clientProfiles: []
    drivers:
      cephfs:
        name: rook-ceph.cephfs.csi.ceph.com
      nfs:
        enabled: false
      nvmeof:
        enabled: false
      rbd:
        name: rook-ceph.rbd.csi.ceph.com
        snapshotPolicy: volumeSnapshot
    operatorConfig:
      driverSpecDefaults:
        kernelMountOptions:
          ms_mode: prefer-crc
        controllerPlugin:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - talos-w-01
                          - talos-w-02
                          - talos-gpu-01
