---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: memini
spec:
  targetNamespace: cortex
  commonMetadata:
    labels:
      app.kubernetes.io/name: memini
  path: ./kubernetes/apps/cortex/memini/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: text-embeddings-inference
