---
komga:
  eventListener:
    enabled: true
    metadataLibraryFilter: []
    metadataSeriesExcludeFilter: []
    notificationsLibraryFilter: []
  metadataUpdate:
    default:
      libraryType: "MANGA"
      updateModes:
        - API
        - COMIC_INFO
      aggregate: true
      mergeTags: true
      mergeGenres: true
      bookCovers: true
      seriesCovers: true
      overrideExistingCovers: true
      overrideComicInfo: true
      postProcessing:
        seriesTitle: true
        seriesTitleLanguage: "en"
        fallbackToAltTitle: false
        alternativeSeriesTitles: false
        alternativeSeriesTitleLanguages:
          - "en"
          - "ja"
          - "ja-ro"
        orderBooks: true
        scoreTagName: "score"
        readingDirectionValue:
        languageValue:
        originalPublisherTagName:

database:
  file: /config/database.sqlite

metadataProviders:
  defaultProviders:
    mangaUpdates:
      priority: 10
      enabled: true
      mediaType: "MANGA"
      authorRoles:
        - "WRITER"
      artistRoles:
        - "PENCILLER"
        - "INKER"
        - "COLORIST"
        - "LETTERER"
        - "COVER"
    nautiljon:
      priority: 30
      enabled: false
    aniList:
      priority: 40
      enabled: true
      mediaType: "MANGA"
      tagsScoreThreshold: 60
      tagsSizeLimit: 15
    yenPress:
      priority: 50
      enabled: false
      mediaType: "MANGA"
    kodansha:
      priority: 60
      enabled: false
    viz:
      priority: 70
      enabled: false
    bookWalker:
      priority: 80
      enabled: true
      mediaType: "MANGA"
    mangaDex:
      priority: 90
      enabled: true
      coverLanguages:
        - "en"
        - "ja"
    bangumi:
      priority: 100
      enabled: false
    comicVine:
      priority: 110
      enabled: false
    hentag:
      priority: 120
      enabled: false
    webtoons:
      priority: 130
      enabled: false
    mangaBaka:
      priority: 140
      enabled: false
      mode: API

logLevel: INFO