# === Networking ===
server.ip = "0.0.0.0"
server.port = 4567

# === Web UI ===
server.webUIEnabled = true
server.initialOpenInBrowserEnabled = false
server.webUIInterface = "browser"
server.webUIFlavor = "WebUI"
server.webUIChannel = "preview"
server.webUIUpdateCheckInterval = 23

# === Downloads ===
server.downloadAsCbz = true
server.downloadsPath = "/home/suwayomi/.local/share/Tachidesk/downloads/mangas"
server.autoDownloadNewChapters = true
server.excludeEntryWithUnreadChapters = false
server.autoDownloadNewChaptersLimit = 0
server.autoDownloadIgnoreReUploads = true

# === FlareSolverr ===
server.flareSolverrEnabled = true
server.flareSolverrUrl = "http://flaresolverr.media.svc.cluster.local:8191"
server.flareSolverrTimeout = 60
server.flareSolverrSessionName = "suwayomi"
server.flareSolverrSessionTtl = 15
server.flareSolverrAsResponseFallback = false

# === Extension Repos ===
server.extensionRepos = [
  "https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json",
  "https://raw.githubusercontent.com/yuzono/manga-repo/repo/index.min.json"
]

# === Misc ===
server.debugLogsEnabled = false
server.systemTrayEnabled = false
server.maxSourcesInParallel = 6
server.maxLogFiles = 14
server.maxLogFileSize = "10mb"
server.maxLogFolderSize = "100mb"
