---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: "${APP}"
spec:
  oidc:
    clientID: "${APP}"
    clientSecret:
      name: "${APP}"
    forwardAccessToken: false
    provider:
      issuer: https://auth.dcunha.io
    redirectURL: "https://${APP}.dcunha.io/oauth2/callback"
    refreshToken: true
    scopes:
      - openid
      - profile
      - email
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "${APP}"
