---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentmemory
spec:
  dataFrom:
    - extract:
        key: agentmemory
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: agentmemory
    template:
      data:
        AGENTMEMORY_SECRET: "{{ .AGENTMEMORY_SECRET }}"
