---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        POSTGRES_PASSWORD: "{{ .DB_PASSWORD }}"
        immich.json: |
          {
            "oauth": {
              "enabled": true,
              "issuerUrl": "https://auth.dcunha.io",
              "clientId": "immich",
              "clientSecret": "{{ .IMMICH_OIDC_CLIENT_SECRET }}",
              "scope": "openid profile email",
              "buttonText": "Login with Pocket ID",
              "autoRegister": true,
              "autoLaunch": false,
              "mobileOverrideEnabled": true,
              "mobileRedirectUri": "https://photos.dcunha.io/api/oauth/mobile-redirect"
            },
            "storageTemplate": {
              "enabled": true,
              "template": "{{ `{{y}}/{{MM}}/{{y}}-{{MM}}-{{dd}}/{{filename}}` }}"
            }
          }
  dataFrom:
    - extract:
        key: immich
