---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-database
spec:
  chartRef:
    kind: OCIRepository
    name: paperless-database
  interval: 1h
  values:
    controllers:
      valkey:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
        containers:
          app:
            image:
              repository: docker.io/valkey/valkey
              tag: 9-alpine
            args:
              - --save
              - ""
              - --appendonly
              - "no"
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    service:
      valkey:
        controller: valkey
        ports:
          valkey:
            port: 6379
