---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-database
spec:
  chartRef:
    kind: OCIRepository
    name: paperless-database
  interval: 1h
  values:
    controllers:
      valkey:
        pod:
          securityContext:
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
        containers:
          app:
            image:
              repository: docker.io/valkey/valkey
              tag: 9.0.4-alpine@sha256:aba3ce55601d0cf7e121fc3c5d9e23bea99bd0df5466500df46c157313226d2e
            args:
              - --save
              - ""
              - --appendonly
              - "no"
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    service:
      valkey:
        controller: valkey
        ports:
          valkey:
            port: 6379
