---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-metrics
spec:
  dataFrom:
    - extract:
        key: forgejo-metrics
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-metrics
    template:
      data:
        METRICS_TOKEN: "{{ .METRICS_TOKEN }}"
