---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.victoriametrics.com/vmstaticscrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: gatus-frostlink
spec:
  targetEndpoints:
    - targets:
        - status.dcunha.io
      path: /metrics
      scheme: https
      scrapeTimeout: 30s
      relabelConfigs:
        - action: replace
          targetLabel: job
          replacement: gatus
        - action: replace
          targetLabel: instance
          replacement: frostlink
