---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: wings
  labels:
    kubernetes.io/service-name: wings
addressType: IPv4
endpoints:
  - addresses:
      - 10.10.99.25
    conditions:
      ready: true
      serving: true
      terminating: false
ports:
  - name: http
    port: 8080
    protocol: TCP
    appProtocol: http
