---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname sparkyfitness
spec:
  dataFrom:
    - extract:
        key: sparkyfitness
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        BETTER_AUTH_SECRET: "{{ .BETTER_AUTH_SECRET }}"
        SPARKY_FITNESS_ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
        SPARKY_FITNESS_API_ENCRYPTION_KEY: "{{ .API_ENCRYPTION_KEY }}"
