---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: llmkube
spec:
  chartRef:
    kind: OCIRepository
    name: llmkube
  interval: 30m
  values:
    controllerManager:
      leaderElection:
        enabled: false
      podSecurityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      replicaCount: 1
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
    crds:
      install: true
      keep: true
    metrics:
      secure: false
    modelCache:
      accessMode: ReadWriteOnce
      enabled: true
      mode: perService
      mountPath: /models
      size: 4Gi
      storageClass: miroir
    namespace: cortex
    prometheus:
      inferencePodMonitor:
        enabled: true
        additionalLabels: {}
      serviceMonitor:
        enabled: true
        additionalLabels: {}
