---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname searxng
spec:
  dataFrom:
    - extract:
        key: searxng
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      data:
        SEARXNG_METRICS_USER: metrics
        SEARXNG_OPEN_METRICS: "{{ .SEARXNG_OPEN_METRICS }}"
        SEARXNG_SECRET: "{{ .SEARXNG_SECRET }}"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretname searxng-settings
spec:
  dataFrom:
    - extract:
        key: searxng
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretname
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: searxng-config
            items:
              - key: settings.yml
