---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  chartRef:
    kind: OCIRepository
    name: searxng
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
    controllers:
      searxng:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2026.9.1-79c8ffe0d@sha256:ae889f0ba120b0333e74c6f760bec6fa54e3d581dafc5d7d7647bc05cd57e491
            env:
              SEARXNG_BASE_URL: "https://searxng.dcunha.io"
              SEARXNG_PORT: "8080"
            envFrom:
              - secretRef:
                  name: searxng
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /stats
                    port: &port 8080
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /stats
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
    persistence:
      config:
        type: secret
        name: searxng-settings
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
      tmp:
        type: emptyDir
        advancedMounts:
          searxng:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
