---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-webhook-token
spec:
  dataFrom:
    - extract:
        key: forgejo
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flux-webhook-token
    template:
      data:
        token: "{{ .FLUX_WEBHOOK_TOKEN }}"
      engineVersion: v2
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosign-public-key
spec:
  dataFrom:
    - extract:
        key: cosign
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cosign-public-key
    template:
      data:
        cosign.pub: "{{ .COSIGN_PUB_KEY | b64dec }}"
      engineVersion: v2
