---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kamiyomu
spec:
  chartRef:
    kind: OCIRepository
    name: kamiyomu
  interval: 1h
  values:
    controllers:
      kamiyomu:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: marcoscostadev/kamiyomu
              tag: 1.2.1@sha256:62219889247891a7ef34fa5608f3d167211ff3c7334e980e6b268f7a51217b87
            env:
              TZ: America/Toronto
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  failureThreshold: 30
            resources:
              requests:
                cpu: 15m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "kamiyomu.dcunha.io"
        parentRefs:
          - name: internal-gateway
            namespace: network

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          kamiyomu:
            app:
              - path: /db
                subPath: db
              - path: /agents
                subPath: agents
      logs:
        type: emptyDir
        globalMounts:
          - path: /logs
      media:
        type: nfs
        server: 10.10.99.100
        path: /mnt/atlas/media
        globalMounts:
          - path: /manga
            subPath: manga
