---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fingerjoin
spec:
  chartRef:
    kind: OCIRepository
    name: fingerjoin
  interval: 1h
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/exikle/fingerjoin
              tag: master@sha256:1ae5464bb38d5f61974aae48003836ac260d8f3f04a11d7b540e61b684b3cd11
            env:
              RUST_LOG: fingerjoin=info,tower_http=info
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 400"]
        hostnames:
          - dcunha.io
        parentRefs:
          - name: external-gateway
            namespace: network
            sectionName: https
        rules:
          - matches:
              - path:
                  type: Exact
                  value: /.well-known/webfinger
            backendRefs:
              - identifier: main
                port: 80
