---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fingerjoin
spec:
  chartRef:
    kind: OCIRepository
    name: fingerjoin
  interval: 1h
  values:
    controllers:
      main:
        containers:
          main:
            env:
              RUST_LOG: fingerjoin=info,tower_http=info
    route:
      app:
        hostnames:
          - dcunha.io
        parentRefs:
          - name: external-gateway
            namespace: network
            sectionName: https
        rules:
          - matches:
              - path:
                  type: Exact
                  value: /.well-known/webfinger
            backendRefs:
              - identifier: main
                port: 80
